/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  LoginData,
  LogoutRequest,
  Passkey,
  ResetPassword,
  ResetPasswordRequest,
  SessionInfo,
  Token,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LoginDataFromJSON,
    LoginDataToJSON,
    LogoutRequestFromJSON,
    LogoutRequestToJSON,
    PasskeyFromJSON,
    PasskeyToJSON,
    ResetPasswordFromJSON,
    ResetPasswordToJSON,
    ResetPasswordRequestFromJSON,
    ResetPasswordRequestToJSON,
    SessionInfoFromJSON,
    SessionInfoToJSON,
    TokenFromJSON,
    TokenToJSON,
} from '../models/index';

export interface DeletePasskeyApiV1WebauthnCredentialIdDeleteRequest {
    credentialId: string;
}

export interface LogoutApiV1AuthLogoutPostRequest {
    logoutRequest?: LogoutRequest;
}

export interface ProcessLoginApiV1AuthLoginPostRequest {
    loginData: LoginData;
}

export interface RegisterPasskeyApiV1WebauthnRegisterPostRequest {
    requestBody: { [key: string]: any; };
}

export interface ResetPasswordApiV1AuthResetPostRequest {
    token: string;
    resetPassword: ResetPassword;
}

export interface ResetPasswordRequestApiV1AuthResetPasswordRequestPostRequest {
    resetPasswordRequest: ResetPasswordRequest;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Delete Passkey
     */
    async deletePasskeyApiV1WebauthnCredentialIdDeleteRaw(requestParameters: DeletePasskeyApiV1WebauthnCredentialIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['credentialId'] == null) {
            throw new runtime.RequiredError(
                'credentialId',
                'Required parameter "credentialId" was null or undefined when calling deletePasskeyApiV1WebauthnCredentialIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/webauthn/{credential_id}`.replace(`{${"credential_id"}}`, encodeURIComponent(String(requestParameters['credentialId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Passkey
     */
    async deletePasskeyApiV1WebauthnCredentialIdDelete(requestParameters: DeletePasskeyApiV1WebauthnCredentialIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.deletePasskeyApiV1WebauthnCredentialIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Passkeys
     */
    async listPasskeysApiV1WebauthnGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Passkey>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/webauthn/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PasskeyFromJSON));
    }

    /**
     * List Passkeys
     */
    async listPasskeysApiV1WebauthnGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Passkey>> {
        const response = await this.listPasskeysApiV1WebauthnGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Return all accounts currently signed in this browser (multi-account).  Public endpoint (no auth dependency): it only reflects the cookies the caller already holds and never reveals anything about accounts whose signed session cookie is not present.
     * List Sessions
     */
    async listSessionsApiV1AuthSessionsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SessionInfo>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/auth/sessions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SessionInfoFromJSON));
    }

    /**
     * Return all accounts currently signed in this browser (multi-account).  Public endpoint (no auth dependency): it only reflects the cookies the caller already holds and never reveals anything about accounts whose signed session cookie is not present.
     * List Sessions
     */
    async listSessionsApiV1AuthSessionsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SessionInfo>> {
        const response = await this.listSessionsApiV1AuthSessionsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Sign out of a single account and return the remaining sessions.  Deletes only the targeted account\'s session cookie (``account_id`` in the body, defaulting to the active account). Other accounts stay signed in. When no sessions remain the ``active_account`` selector is cleared too. The legacy single-session ``access_token`` cookie is also cleared when it is the thing being logged out, for backward compatibility.
     * Logout
     */
    async logoutApiV1AuthLogoutPostRaw(requestParameters: LogoutApiV1AuthLogoutPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SessionInfo>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/auth/logout`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LogoutRequestToJSON(requestParameters['logoutRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SessionInfoFromJSON));
    }

    /**
     * Sign out of a single account and return the remaining sessions.  Deletes only the targeted account\'s session cookie (``account_id`` in the body, defaulting to the active account). Other accounts stay signed in. When no sessions remain the ``active_account`` selector is cleared too. The legacy single-session ``access_token`` cookie is also cleared when it is the thing being logged out, for backward compatibility.
     * Logout
     */
    async logoutApiV1AuthLogoutPost(requestParameters: LogoutApiV1AuthLogoutPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SessionInfo>> {
        const response = await this.logoutApiV1AuthLogoutPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Prepare Login
     */
    async prepareLoginApiV1AuthLoginGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/auth/login`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Prepare Login
     */
    async prepareLoginApiV1AuthLoginGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.prepareLoginApiV1AuthLoginGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Preregister Passkey
     */
    async preregisterPasskeyApiV1WebauthnPreregisterGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/webauthn/preregister`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Preregister Passkey
     */
    async preregisterPasskeyApiV1WebauthnPreregisterGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.preregisterPasskeyApiV1WebauthnPreregisterGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Process Login
     */
    async processLoginApiV1AuthLoginPostRaw(requestParameters: ProcessLoginApiV1AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>> {
        if (requestParameters['loginData'] == null) {
            throw new runtime.RequiredError(
                'loginData',
                'Required parameter "loginData" was null or undefined when calling processLoginApiV1AuthLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginDataToJSON(requestParameters['loginData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
    }

    /**
     * Process Login
     */
    async processLoginApiV1AuthLoginPost(requestParameters: ProcessLoginApiV1AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token> {
        const response = await this.processLoginApiV1AuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Register Passkey
     */
    async registerPasskeyApiV1WebauthnRegisterPostRaw(requestParameters: RegisterPasskeyApiV1WebauthnRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling registerPasskeyApiV1WebauthnRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/webauthn/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Register Passkey
     */
    async registerPasskeyApiV1WebauthnRegisterPost(requestParameters: RegisterPasskeyApiV1WebauthnRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.registerPasskeyApiV1WebauthnRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reset Password
     */
    async resetPasswordApiV1AuthResetPostRaw(requestParameters: ResetPasswordApiV1AuthResetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling resetPasswordApiV1AuthResetPost().'
            );
        }

        if (requestParameters['resetPassword'] == null) {
            throw new runtime.RequiredError(
                'resetPassword',
                'Required parameter "resetPassword" was null or undefined when calling resetPasswordApiV1AuthResetPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['token'] != null) {
            headerParameters['token'] = String(requestParameters['token']);
        }

        const response = await this.request({
            path: `/api/v1/auth/reset`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResetPasswordToJSON(requestParameters['resetPassword']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Reset Password
     */
    async resetPasswordApiV1AuthResetPost(requestParameters: ResetPasswordApiV1AuthResetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.resetPasswordApiV1AuthResetPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reset Password Request
     */
    async resetPasswordRequestApiV1AuthResetPasswordRequestPostRaw(requestParameters: ResetPasswordRequestApiV1AuthResetPasswordRequestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['resetPasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'resetPasswordRequest',
                'Required parameter "resetPasswordRequest" was null or undefined when calling resetPasswordRequestApiV1AuthResetPasswordRequestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/auth/reset_password_request`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResetPasswordRequestToJSON(requestParameters['resetPasswordRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Reset Password Request
     */
    async resetPasswordRequestApiV1AuthResetPasswordRequestPost(requestParameters: ResetPasswordRequestApiV1AuthResetPasswordRequestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.resetPasswordRequestApiV1AuthResetPasswordRequestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
