/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type LoginCode,
    LoginCodeFromJSON,
    LoginCodeToJSON,
} from '../models/LoginCode';
import {
    type LoginData,
    LoginDataFromJSON,
    LoginDataToJSON,
} from '../models/LoginData';
import {
    type LogoutRequest,
    LogoutRequestFromJSON,
    LogoutRequestToJSON,
} from '../models/LogoutRequest';
import {
    type Passkey,
    PasskeyFromJSON,
    PasskeyToJSON,
} from '../models/Passkey';
import {
    type PasskeySignal,
    PasskeySignalFromJSON,
    PasskeySignalToJSON,
} from '../models/PasskeySignal';
import {
    type RecoveryGrant,
    RecoveryGrantFromJSON,
    RecoveryGrantToJSON,
} from '../models/RecoveryGrant';
import {
    type ResetPasswordRequest,
    ResetPasswordRequestFromJSON,
    ResetPasswordRequestToJSON,
} from '../models/ResetPasswordRequest';
import {
    type SessionInfo,
    SessionInfoFromJSON,
    SessionInfoToJSON,
} from '../models/SessionInfo';
import {
    type SetPassword,
    SetPasswordFromJSON,
    SetPasswordToJSON,
} from '../models/SetPassword';
import {
    type Token,
    TokenFromJSON,
    TokenToJSON,
} from '../models/Token';

export interface DeletePasskeyApiV1WebauthnCredentialIdDeleteRequest {
    /**
     * 
     */
    credentialId: string;
}

export interface LoginWithCodeApiV1AuthLoginCodePostRequest {
    /**
     * 
     */
    loginCode: LoginCode;
}

export interface LogoutApiV1AuthLogoutPostRequest {
    /**
     * 
     */
    logoutRequest?: LogoutRequest | null;
}

export interface PreregisterPasskeyApiV1WebauthnPreregisterGetRequest {
    /**
     * 
     */
    flow?: PreregisterPasskeyApiV1WebauthnPreregisterGetFlowEnum;
}

export interface ProcessLoginApiV1AuthLoginPostRequest {
    /**
     * 
     */
    loginData: LoginData;
}

export interface RegisterPasskeyApiV1WebauthnRegisterPostRequest {
    /**
     * 
     */
    requestBody: { [key: string]: any | null; };
}

export interface ResetPasswordRequestApiV1AuthResetPasswordRequestPostRequest {
    /**
     * 
     */
    resetPasswordRequest: ResetPasswordRequest;
}

export interface SetPasswordApiV1AuthSetPasswordPostRequest {
    /**
     * 
     */
    setPassword: SetPassword;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Creates request options for deletePasskeyApiV1WebauthnCredentialIdDelete without sending the request
     */
    async deletePasskeyApiV1WebauthnCredentialIdDeleteRequestOpts(requestParameters: DeletePasskeyApiV1WebauthnCredentialIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['credentialId'] == null) {
            throw new runtime.RequiredError(
                'credentialId',
                'Required parameter "credentialId" was null or undefined when calling deletePasskeyApiV1WebauthnCredentialIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/webauthn/{credential_id}`;
        urlPath = urlPath.replace('{credential_id}', encodeURIComponent(String(requestParameters['credentialId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a passkey and return the Signal API payload.  The response lists the credentials still valid for this user so the client can call ``PublicKeyCredential.signalAllAcceptedCredentials()``: the passkey provider then deletes its local copy of the removed key immediately, instead of keeping an orphan that would be suggested at the next login and fail.
     * Delete Passkey
     */
    async deletePasskeyApiV1WebauthnCredentialIdDeleteRaw(requestParameters: DeletePasskeyApiV1WebauthnCredentialIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PasskeySignal>> {
        const requestOptions = await this.deletePasskeyApiV1WebauthnCredentialIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PasskeySignalFromJSON(jsonValue));
    }

    /**
     * Delete a passkey and return the Signal API payload.  The response lists the credentials still valid for this user so the client can call ``PublicKeyCredential.signalAllAcceptedCredentials()``: the passkey provider then deletes its local copy of the removed key immediately, instead of keeping an orphan that would be suggested at the next login and fail.
     * Delete Passkey
     */
    async deletePasskeyApiV1WebauthnCredentialIdDelete(requestParameters: DeletePasskeyApiV1WebauthnCredentialIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PasskeySignal> {
        const response = await this.deletePasskeyApiV1WebauthnCredentialIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPasskeysApiV1WebauthnGet without sending the request
     */
    async listPasskeysApiV1WebauthnGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/webauthn/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Passkeys
     */
    async listPasskeysApiV1WebauthnGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Passkey>>> {
        const requestOptions = await this.listPasskeysApiV1WebauthnGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PasskeyFromJSON));
    }

    /**
     * List Passkeys
     */
    async listPasskeysApiV1WebauthnGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Passkey>> {
        const response = await this.listPasskeysApiV1WebauthnGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSessionsApiV1AuthSessionsGet without sending the request
     */
    async listSessionsApiV1AuthSessionsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/auth/sessions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return all accounts currently signed in this browser (multi-account).  Public endpoint (no auth dependency): it only reflects the cookies the caller already holds and never reveals anything about accounts whose signed session cookie is not present.
     * List Sessions
     */
    async listSessionsApiV1AuthSessionsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SessionInfo>>> {
        const requestOptions = await this.listSessionsApiV1AuthSessionsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SessionInfoFromJSON));
    }

    /**
     * Return all accounts currently signed in this browser (multi-account).  Public endpoint (no auth dependency): it only reflects the cookies the caller already holds and never reveals anything about accounts whose signed session cookie is not present.
     * List Sessions
     */
    async listSessionsApiV1AuthSessionsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SessionInfo>> {
        const response = await this.listSessionsApiV1AuthSessionsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for loginWithCodeApiV1AuthLoginCodePost without sending the request
     */
    async loginWithCodeApiV1AuthLoginCodePostRequestOpts(requestParameters: LoginWithCodeApiV1AuthLoginCodePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['loginCode'] == null) {
            throw new runtime.RequiredError(
                'loginCode',
                'Required parameter "loginCode" was null or undefined when calling loginWithCodeApiV1AuthLoginCodePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/login_code`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginCodeToJSON(requestParameters['loginCode']),
        };
    }

    /**
     * Sign the member in from an emailed recovery grant (grant id + code).  Single consumption endpoint of the recovery email, for every account type. The grant id publicly identifies the request; the 6-digit code is the secret (RFC 8628\'s device_code/user_code split). The email offers it two ways: the code to type into the page that requested it — the primary path, keeping the session (and the passkey ceremony that may follow) in a real browser instead of an email app\'s WebView — and a link that is this same call with both fields prefilled in its URL (verification_uri_complete pattern). Also the landing of the welcome email sent when staff creates a member by hand.  Proving control of the email is a full authentication (same reasoning as the invitation-accept flow), so the member lands signed in (additive session cookies, becomes the active account) and the client offers how to secure the next sign-in: a passkey, or a new password for accounts that had one.  Guessing is bounded by the attempt counter (then the grant is revoked) and the grant\'s short lifetime. Every failure returns the same 403 so the endpoint reveals nothing about account existence, pending recoveries, or grant-id validity (decoy grant ids answer identically).
     * Login With Code
     */
    async loginWithCodeApiV1AuthLoginCodePostRaw(requestParameters: LoginWithCodeApiV1AuthLoginCodePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>> {
        const requestOptions = await this.loginWithCodeApiV1AuthLoginCodePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
    }

    /**
     * Sign the member in from an emailed recovery grant (grant id + code).  Single consumption endpoint of the recovery email, for every account type. The grant id publicly identifies the request; the 6-digit code is the secret (RFC 8628\'s device_code/user_code split). The email offers it two ways: the code to type into the page that requested it — the primary path, keeping the session (and the passkey ceremony that may follow) in a real browser instead of an email app\'s WebView — and a link that is this same call with both fields prefilled in its URL (verification_uri_complete pattern). Also the landing of the welcome email sent when staff creates a member by hand.  Proving control of the email is a full authentication (same reasoning as the invitation-accept flow), so the member lands signed in (additive session cookies, becomes the active account) and the client offers how to secure the next sign-in: a passkey, or a new password for accounts that had one.  Guessing is bounded by the attempt counter (then the grant is revoked) and the grant\'s short lifetime. Every failure returns the same 403 so the endpoint reveals nothing about account existence, pending recoveries, or grant-id validity (decoy grant ids answer identically).
     * Login With Code
     */
    async loginWithCodeApiV1AuthLoginCodePost(requestParameters: LoginWithCodeApiV1AuthLoginCodePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token> {
        const response = await this.loginWithCodeApiV1AuthLoginCodePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for logoutApiV1AuthLogoutPost without sending the request
     */
    async logoutApiV1AuthLogoutPostRequestOpts(requestParameters: LogoutApiV1AuthLogoutPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/logout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LogoutRequestToJSON(requestParameters['logoutRequest']),
        };
    }

    /**
     * Sign out of a single account and return the remaining sessions.  Deletes only the targeted account\'s session cookie (``account_id`` in the body, defaulting to the active account). Other accounts stay signed in. When no sessions remain the ``active_account`` selector is cleared too. The legacy single-session ``access_token`` cookie is also cleared when it is the thing being logged out, for backward compatibility.  When ``all`` is true, every account signed in this browser is signed out at once (``account_id`` is ignored) and an empty list is returned. This only clears cookies in the current browser; sessions on other devices are not revoked (tokens are stateless and carry no server-side session record).
     * Logout
     */
    async logoutApiV1AuthLogoutPostRaw(requestParameters: LogoutApiV1AuthLogoutPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SessionInfo>>> {
        const requestOptions = await this.logoutApiV1AuthLogoutPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SessionInfoFromJSON));
    }

    /**
     * Sign out of a single account and return the remaining sessions.  Deletes only the targeted account\'s session cookie (``account_id`` in the body, defaulting to the active account). Other accounts stay signed in. When no sessions remain the ``active_account`` selector is cleared too. The legacy single-session ``access_token`` cookie is also cleared when it is the thing being logged out, for backward compatibility.  When ``all`` is true, every account signed in this browser is signed out at once (``account_id`` is ignored) and an empty list is returned. This only clears cookies in the current browser; sessions on other devices are not revoked (tokens are stateless and carry no server-side session record).
     * Logout
     */
    async logoutApiV1AuthLogoutPost(requestParameters: LogoutApiV1AuthLogoutPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SessionInfo>> {
        const response = await this.logoutApiV1AuthLogoutPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for prepareLoginApiV1AuthLoginGet without sending the request
     */
    async prepareLoginApiV1AuthLoginGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/auth/login`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Prepare Login
     */
    async prepareLoginApiV1AuthLoginGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.prepareLoginApiV1AuthLoginGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Prepare Login
     */
    async prepareLoginApiV1AuthLoginGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.prepareLoginApiV1AuthLoginGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for preregisterPasskeyApiV1WebauthnPreregisterGet without sending the request
     */
    async preregisterPasskeyApiV1WebauthnPreregisterGetRequestOpts(requestParameters: PreregisterPasskeyApiV1WebauthnPreregisterGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['flow'] != null) {
            queryParameters['flow'] = requestParameters['flow'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/webauthn/preregister`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Preregister Passkey
     */
    async preregisterPasskeyApiV1WebauthnPreregisterGetRaw(requestParameters: PreregisterPasskeyApiV1WebauthnPreregisterGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.preregisterPasskeyApiV1WebauthnPreregisterGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Preregister Passkey
     */
    async preregisterPasskeyApiV1WebauthnPreregisterGet(requestParameters: PreregisterPasskeyApiV1WebauthnPreregisterGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.preregisterPasskeyApiV1WebauthnPreregisterGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for processLoginApiV1AuthLoginPost without sending the request
     */
    async processLoginApiV1AuthLoginPostRequestOpts(requestParameters: ProcessLoginApiV1AuthLoginPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['loginData'] == null) {
            throw new runtime.RequiredError(
                'loginData',
                'Required parameter "loginData" was null or undefined when calling processLoginApiV1AuthLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginDataToJSON(requestParameters['loginData']),
        };
    }

    /**
     * Process Login
     */
    async processLoginApiV1AuthLoginPostRaw(requestParameters: ProcessLoginApiV1AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>> {
        const requestOptions = await this.processLoginApiV1AuthLoginPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
    }

    /**
     * Process Login
     */
    async processLoginApiV1AuthLoginPost(requestParameters: ProcessLoginApiV1AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token> {
        const response = await this.processLoginApiV1AuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerPasskeyApiV1WebauthnRegisterPost without sending the request
     */
    async registerPasskeyApiV1WebauthnRegisterPostRequestOpts(requestParameters: RegisterPasskeyApiV1WebauthnRegisterPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling registerPasskeyApiV1WebauthnRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/webauthn/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     * Register Passkey
     */
    async registerPasskeyApiV1WebauthnRegisterPostRaw(requestParameters: RegisterPasskeyApiV1WebauthnRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.registerPasskeyApiV1WebauthnRegisterPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Register Passkey
     */
    async registerPasskeyApiV1WebauthnRegisterPost(requestParameters: RegisterPasskeyApiV1WebauthnRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.registerPasskeyApiV1WebauthnRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resetPasswordRequestApiV1AuthResetPasswordRequestPost without sending the request
     */
    async resetPasswordRequestApiV1AuthResetPasswordRequestPostRequestOpts(requestParameters: ResetPasswordRequestApiV1AuthResetPasswordRequestPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resetPasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'resetPasswordRequest',
                'Required parameter "resetPasswordRequest" was null or undefined when calling resetPasswordRequestApiV1AuthResetPasswordRequestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/reset_password_request`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResetPasswordRequestToJSON(requestParameters['resetPasswordRequest']),
        };
    }

    /**
     * Reset Password Request
     */
    async resetPasswordRequestApiV1AuthResetPasswordRequestPostRaw(requestParameters: ResetPasswordRequestApiV1AuthResetPasswordRequestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecoveryGrant>> {
        const requestOptions = await this.resetPasswordRequestApiV1AuthResetPasswordRequestPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecoveryGrantFromJSON(jsonValue));
    }

    /**
     * Reset Password Request
     */
    async resetPasswordRequestApiV1AuthResetPasswordRequestPost(requestParameters: ResetPasswordRequestApiV1AuthResetPasswordRequestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecoveryGrant> {
        const response = await this.resetPasswordRequestApiV1AuthResetPasswordRequestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setPasswordApiV1AuthSetPasswordPost without sending the request
     */
    async setPasswordApiV1AuthSetPasswordPostRequestOpts(requestParameters: SetPasswordApiV1AuthSetPasswordPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['setPassword'] == null) {
            throw new runtime.RequiredError(
                'setPassword',
                'Required parameter "setPassword" was null or undefined when calling setPasswordApiV1AuthSetPasswordPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/auth/set_password`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetPasswordToJSON(requestParameters['setPassword']),
        };
    }

    /**
     * Set (or replace) the signed-in member\'s password.  Recovery successor of the old ``POST /auth/reset``: proving control of the email (code or link) already signed the member in, so setting a new password is now an authenticated action instead of a token-bearing one. Deliberately does not require the current password — the flow exists precisely because it was forgotten. The trust boundary is kept at \"proved email control recently\" by requiring a FRESH session (see ``SET_PASSWORD_MAX_SESSION_AGE``): without it, any live session (they last 90 days and cannot be revoked) could quietly take over the account with a password of its own. Also usable later from the account-security settings for members who want a fallback password, behind a fresh re-authentication.
     * Set Password
     */
    async setPasswordApiV1AuthSetPasswordPostRaw(requestParameters: SetPasswordApiV1AuthSetPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.setPasswordApiV1AuthSetPasswordPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Set (or replace) the signed-in member\'s password.  Recovery successor of the old ``POST /auth/reset``: proving control of the email (code or link) already signed the member in, so setting a new password is now an authenticated action instead of a token-bearing one. Deliberately does not require the current password — the flow exists precisely because it was forgotten. The trust boundary is kept at \"proved email control recently\" by requiring a FRESH session (see ``SET_PASSWORD_MAX_SESSION_AGE``): without it, any live session (they last 90 days and cannot be revoked) could quietly take over the account with a password of its own. Also usable later from the account-security settings for members who want a fallback password, behind a fresh re-authentication.
     * Set Password
     */
    async setPasswordApiV1AuthSetPasswordPost(requestParameters: SetPasswordApiV1AuthSetPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.setPasswordApiV1AuthSetPasswordPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for verifyEmailAccessApiV1AuthVerifyGet without sending the request
     */
    async verifyEmailAccessApiV1AuthVerifyGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/auth/verify`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Forward-auth gate for the Mailpit UI (beta).  Reachable through Traefik\'s ``forwardAuth`` middleware, which replays the caller\'s cookies here before serving the internal Mailpit service. A 204 means the browser holds a valid session whose role grants ``VIEW:EMAIL`` (staff/admin); the ``Authorization`` dependency raises 401/403 otherwise. The body is empty on purpose: only the status code matters to Traefik.
     * Verify Email Access
     */
    async verifyEmailAccessApiV1AuthVerifyGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.verifyEmailAccessApiV1AuthVerifyGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Forward-auth gate for the Mailpit UI (beta).  Reachable through Traefik\'s ``forwardAuth`` middleware, which replays the caller\'s cookies here before serving the internal Mailpit service. A 204 means the browser holds a valid session whose role grants ``VIEW:EMAIL`` (staff/admin); the ``Authorization`` dependency raises 401/403 otherwise. The body is empty on purpose: only the status code matters to Traefik.
     * Verify Email Access
     */
    async verifyEmailAccessApiV1AuthVerifyGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.verifyEmailAccessApiV1AuthVerifyGetRaw(initOverrides);
    }

}

/**
 * @export
 */
export const PreregisterPasskeyApiV1WebauthnPreregisterGetFlowEnum = {
    Explicit: 'explicit',
    Silent: 'silent',
} as const;
export type PreregisterPasskeyApiV1WebauthnPreregisterGetFlowEnum = typeof PreregisterPasskeyApiV1WebauthnPreregisterGetFlowEnum[keyof typeof PreregisterPasskeyApiV1WebauthnPreregisterGetFlowEnum];
