/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Campaign,
  CampaignCreate,
  CampaignListItem,
  CampaignUpdate,
  HTTPValidationError,
} from '../models/index';
import {
    CampaignFromJSON,
    CampaignToJSON,
    CampaignCreateFromJSON,
    CampaignCreateToJSON,
    CampaignListItemFromJSON,
    CampaignListItemToJSON,
    CampaignUpdateFromJSON,
    CampaignUpdateToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface ArchiveCampaignApiV1CampaignsCampaignIdArchivePostRequest {
    campaignId: number;
    authorization?: string | null;
    accessToken?: string | null;
}

export interface CreateCampaignApiV1CampaignsPostRequest {
    campaignCreate: CampaignCreate;
    authorization?: string | null;
    accessToken?: string | null;
}

export interface DeleteCampaignApiV1CampaignsCampaignIdDeleteRequest {
    campaignId: number;
    authorization?: string | null;
    accessToken?: string | null;
}

export interface GetCampaignApiV1CampaignsCampaignIdGetRequest {
    campaignId: number;
    authorization?: string | null;
    accessToken?: string | null;
}

export interface LinkEventApiV1CampaignsCampaignIdEventsEventIdPostRequest {
    campaignId: number;
    eventId: number;
    authorization?: string | null;
    accessToken?: string | null;
}

export interface ListCampaignsApiV1CampaignsGetRequest {
    authorization?: string | null;
    accessToken?: string | null;
}

export interface PublishCampaignApiV1CampaignsCampaignIdPublishPostRequest {
    campaignId: number;
    authorization?: string | null;
    accessToken?: string | null;
}

export interface UnlinkEventApiV1CampaignsCampaignIdEventsEventIdDeleteRequest {
    campaignId: number;
    eventId: number;
    authorization?: string | null;
    accessToken?: string | null;
}

export interface UpdateCampaignApiV1CampaignsCampaignIdPatchRequest {
    campaignId: number;
    campaignUpdate: CampaignUpdate;
    authorization?: string | null;
    accessToken?: string | null;
}

/**
 * 
 */
export class CampaignsApi extends runtime.BaseAPI {

    /**
     * Archive Campaign
     */
    async archiveCampaignApiV1CampaignsCampaignIdArchivePostRaw(requestParameters: ArchiveCampaignApiV1CampaignsCampaignIdArchivePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Campaign>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling archiveCampaignApiV1CampaignsCampaignIdArchivePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/v1/campaigns/{campaign_id}/archive`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CampaignFromJSON(jsonValue));
    }

    /**
     * Archive Campaign
     */
    async archiveCampaignApiV1CampaignsCampaignIdArchivePost(requestParameters: ArchiveCampaignApiV1CampaignsCampaignIdArchivePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Campaign> {
        const response = await this.archiveCampaignApiV1CampaignsCampaignIdArchivePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Campaign
     */
    async createCampaignApiV1CampaignsPostRaw(requestParameters: CreateCampaignApiV1CampaignsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Campaign>> {
        if (requestParameters['campaignCreate'] == null) {
            throw new runtime.RequiredError(
                'campaignCreate',
                'Required parameter "campaignCreate" was null or undefined when calling createCampaignApiV1CampaignsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/v1/campaigns/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CampaignCreateToJSON(requestParameters['campaignCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CampaignFromJSON(jsonValue));
    }

    /**
     * Create Campaign
     */
    async createCampaignApiV1CampaignsPost(requestParameters: CreateCampaignApiV1CampaignsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Campaign> {
        const response = await this.createCampaignApiV1CampaignsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Campaign
     */
    async deleteCampaignApiV1CampaignsCampaignIdDeleteRaw(requestParameters: DeleteCampaignApiV1CampaignsCampaignIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling deleteCampaignApiV1CampaignsCampaignIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/v1/campaigns/{campaign_id}`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Campaign
     */
    async deleteCampaignApiV1CampaignsCampaignIdDelete(requestParameters: DeleteCampaignApiV1CampaignsCampaignIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCampaignApiV1CampaignsCampaignIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get Campaign
     */
    async getCampaignApiV1CampaignsCampaignIdGetRaw(requestParameters: GetCampaignApiV1CampaignsCampaignIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Campaign>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling getCampaignApiV1CampaignsCampaignIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/v1/campaigns/{campaign_id}`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CampaignFromJSON(jsonValue));
    }

    /**
     * Get Campaign
     */
    async getCampaignApiV1CampaignsCampaignIdGet(requestParameters: GetCampaignApiV1CampaignsCampaignIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Campaign> {
        const response = await this.getCampaignApiV1CampaignsCampaignIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Link Event
     */
    async linkEventApiV1CampaignsCampaignIdEventsEventIdPostRaw(requestParameters: LinkEventApiV1CampaignsCampaignIdEventsEventIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling linkEventApiV1CampaignsCampaignIdEventsEventIdPost().'
            );
        }

        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling linkEventApiV1CampaignsCampaignIdEventsEventIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/v1/campaigns/{campaign_id}/events/{event_id}`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))).replace(`{${"event_id"}}`, encodeURIComponent(String(requestParameters['eventId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Link Event
     */
    async linkEventApiV1CampaignsCampaignIdEventsEventIdPost(requestParameters: LinkEventApiV1CampaignsCampaignIdEventsEventIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.linkEventApiV1CampaignsCampaignIdEventsEventIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Campaigns
     */
    async listCampaignsApiV1CampaignsGetRaw(requestParameters: ListCampaignsApiV1CampaignsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CampaignListItem>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/v1/campaigns/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CampaignListItemFromJSON));
    }

    /**
     * List Campaigns
     */
    async listCampaignsApiV1CampaignsGet(requestParameters: ListCampaignsApiV1CampaignsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CampaignListItem>> {
        const response = await this.listCampaignsApiV1CampaignsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Publish Campaign
     */
    async publishCampaignApiV1CampaignsCampaignIdPublishPostRaw(requestParameters: PublishCampaignApiV1CampaignsCampaignIdPublishPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Campaign>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling publishCampaignApiV1CampaignsCampaignIdPublishPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/v1/campaigns/{campaign_id}/publish`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CampaignFromJSON(jsonValue));
    }

    /**
     * Publish Campaign
     */
    async publishCampaignApiV1CampaignsCampaignIdPublishPost(requestParameters: PublishCampaignApiV1CampaignsCampaignIdPublishPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Campaign> {
        const response = await this.publishCampaignApiV1CampaignsCampaignIdPublishPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unlink Event
     */
    async unlinkEventApiV1CampaignsCampaignIdEventsEventIdDeleteRaw(requestParameters: UnlinkEventApiV1CampaignsCampaignIdEventsEventIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling unlinkEventApiV1CampaignsCampaignIdEventsEventIdDelete().'
            );
        }

        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling unlinkEventApiV1CampaignsCampaignIdEventsEventIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/v1/campaigns/{campaign_id}/events/{event_id}`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))).replace(`{${"event_id"}}`, encodeURIComponent(String(requestParameters['eventId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Unlink Event
     */
    async unlinkEventApiV1CampaignsCampaignIdEventsEventIdDelete(requestParameters: UnlinkEventApiV1CampaignsCampaignIdEventsEventIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.unlinkEventApiV1CampaignsCampaignIdEventsEventIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Update Campaign
     */
    async updateCampaignApiV1CampaignsCampaignIdPatchRaw(requestParameters: UpdateCampaignApiV1CampaignsCampaignIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Campaign>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling updateCampaignApiV1CampaignsCampaignIdPatch().'
            );
        }

        if (requestParameters['campaignUpdate'] == null) {
            throw new runtime.RequiredError(
                'campaignUpdate',
                'Required parameter "campaignUpdate" was null or undefined when calling updateCampaignApiV1CampaignsCampaignIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/v1/campaigns/{campaign_id}`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CampaignUpdateToJSON(requestParameters['campaignUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CampaignFromJSON(jsonValue));
    }

    /**
     * Update Campaign
     */
    async updateCampaignApiV1CampaignsCampaignIdPatch(requestParameters: UpdateCampaignApiV1CampaignsCampaignIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Campaign> {
        const response = await this.updateCampaignApiV1CampaignsCampaignIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
