/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Event,
  EventCreate,
  HTTPValidationError,
  Response,
  ResponseCreate,
} from '../models/index';
import {
    EventFromJSON,
    EventToJSON,
    EventCreateFromJSON,
    EventCreateToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ResponseFromJSON,
    ResponseToJSON,
    ResponseCreateFromJSON,
    ResponseCreateToJSON,
} from '../models/index';

export interface CreateEventApiV1EventsPostRequest {
    eventCreate: EventCreate;
}

export interface CreateResponseApiV1EventsEventIdResponsesPutRequest {
    eventId: number;
    responseCreate: ResponseCreate;
}

export interface DeleteEventApiV1EventsEventIdDeleteRequest {
    eventId: string;
}

export interface GetEventApiV1EventsEventIdGetRequest {
    eventId: string;
}

export interface ListResponsesApiV1ResponsesGetRequest {
    userId?: string | null;
}

export interface UpdateEventApiV1EventsEventIdPutRequest {
    eventId: number;
    eventCreate: EventCreate;
}

/**
 * 
 */
export class EventsApi extends runtime.BaseAPI {

    /**
     * Create Event
     */
    async createEventApiV1EventsPostRaw(requestParameters: CreateEventApiV1EventsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Event>> {
        if (requestParameters.eventCreate === null || requestParameters.eventCreate === undefined) {
            throw new runtime.RequiredError('eventCreate','Required parameter requestParameters.eventCreate was null or undefined when calling createEventApiV1EventsPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2AuthorizationCodeBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/events/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EventCreateToJSON(requestParameters.eventCreate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventFromJSON(jsonValue));
    }

    /**
     * Create Event
     */
    async createEventApiV1EventsPost(requestParameters: CreateEventApiV1EventsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Event> {
        const response = await this.createEventApiV1EventsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Response
     */
    async createResponseApiV1EventsEventIdResponsesPutRaw(requestParameters: CreateResponseApiV1EventsEventIdResponsesPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.eventId === null || requestParameters.eventId === undefined) {
            throw new runtime.RequiredError('eventId','Required parameter requestParameters.eventId was null or undefined when calling createResponseApiV1EventsEventIdResponsesPut.');
        }

        if (requestParameters.responseCreate === null || requestParameters.responseCreate === undefined) {
            throw new runtime.RequiredError('responseCreate','Required parameter requestParameters.responseCreate was null or undefined when calling createResponseApiV1EventsEventIdResponsesPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2AuthorizationCodeBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/events/{event_id}/responses`.replace(`{${"event_id"}}`, encodeURIComponent(String(requestParameters.eventId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ResponseCreateToJSON(requestParameters.responseCreate),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create Response
     */
    async createResponseApiV1EventsEventIdResponsesPut(requestParameters: CreateResponseApiV1EventsEventIdResponsesPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createResponseApiV1EventsEventIdResponsesPutRaw(requestParameters, initOverrides);
    }

    /**
     * Delete Event
     */
    async deleteEventApiV1EventsEventIdDeleteRaw(requestParameters: DeleteEventApiV1EventsEventIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.eventId === null || requestParameters.eventId === undefined) {
            throw new runtime.RequiredError('eventId','Required parameter requestParameters.eventId was null or undefined when calling deleteEventApiV1EventsEventIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2AuthorizationCodeBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/events/{event_id}`.replace(`{${"event_id"}}`, encodeURIComponent(String(requestParameters.eventId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Event
     */
    async deleteEventApiV1EventsEventIdDelete(requestParameters: DeleteEventApiV1EventsEventIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteEventApiV1EventsEventIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Export Ics
     */
    async exportIcsApiV1EventsExportIcsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2AuthorizationCodeBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/events/export/ics`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Export Ics
     */
    async exportIcsApiV1EventsExportIcsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.exportIcsApiV1EventsExportIcsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get Event
     */
    async getEventApiV1EventsEventIdGetRaw(requestParameters: GetEventApiV1EventsEventIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Event>> {
        if (requestParameters.eventId === null || requestParameters.eventId === undefined) {
            throw new runtime.RequiredError('eventId','Required parameter requestParameters.eventId was null or undefined when calling getEventApiV1EventsEventIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2AuthorizationCodeBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/events/{event_id}`.replace(`{${"event_id"}}`, encodeURIComponent(String(requestParameters.eventId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventFromJSON(jsonValue));
    }

    /**
     * Get Event
     */
    async getEventApiV1EventsEventIdGet(requestParameters: GetEventApiV1EventsEventIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Event> {
        const response = await this.getEventApiV1EventsEventIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Events
     */
    async listEventsApiV1EventsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Event>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2AuthorizationCodeBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/events/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EventFromJSON));
    }

    /**
     * List Events
     */
    async listEventsApiV1EventsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Event>> {
        const response = await this.listEventsApiV1EventsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Responses
     */
    async listResponsesApiV1ResponsesGetRaw(requestParameters: ListResponsesApiV1ResponsesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Response>>> {
        const queryParameters: any = {};

        if (requestParameters.userId !== undefined) {
            queryParameters['user_id'] = requestParameters.userId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2AuthorizationCodeBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/responses/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ResponseFromJSON));
    }

    /**
     * List Responses
     */
    async listResponsesApiV1ResponsesGet(requestParameters: ListResponsesApiV1ResponsesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Response>> {
        const response = await this.listResponsesApiV1ResponsesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Event
     */
    async updateEventApiV1EventsEventIdPutRaw(requestParameters: UpdateEventApiV1EventsEventIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Event>> {
        if (requestParameters.eventId === null || requestParameters.eventId === undefined) {
            throw new runtime.RequiredError('eventId','Required parameter requestParameters.eventId was null or undefined when calling updateEventApiV1EventsEventIdPut.');
        }

        if (requestParameters.eventCreate === null || requestParameters.eventCreate === undefined) {
            throw new runtime.RequiredError('eventCreate','Required parameter requestParameters.eventCreate was null or undefined when calling updateEventApiV1EventsEventIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2AuthorizationCodeBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/events/{event_id}`.replace(`{${"event_id"}}`, encodeURIComponent(String(requestParameters.eventId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EventCreateToJSON(requestParameters.eventCreate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventFromJSON(jsonValue));
    }

    /**
     * Update Event
     */
    async updateEventApiV1EventsEventIdPut(requestParameters: UpdateEventApiV1EventsEventIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Event> {
        const response = await this.updateEventApiV1EventsEventIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
