/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FileOrFolder,
  FileOrFolderType,
  FileOrFolderUpdate,
  FolderCreate,
  HTTPValidationError,
} from '../models/index';
import {
    FileOrFolderFromJSON,
    FileOrFolderToJSON,
    FileOrFolderTypeFromJSON,
    FileOrFolderTypeToJSON,
    FileOrFolderUpdateFromJSON,
    FileOrFolderUpdateToJSON,
    FolderCreateFromJSON,
    FolderCreateToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateFolderApiV1FilesFolderIdPostRequest {
    folderId: number;
    folderCreate: FolderCreate;
}

export interface DeleteFileApiV1FilesFileIdDeleteRequest {
    fileId: number;
}

export interface GetBreadcrumbApiV1FilesFileIdBreadcrumbGetRequest {
    fileId: number;
}

export interface GetFileApiV1FilesFileIdGetRequest {
    fileId: number;
}

export interface ListChildrenApiV1FilesFolderIdChildrenGetRequest {
    folderId: number;
}

export interface ListFilesApiV1FilesGetRequest {
    t?: FileOrFolderType | null;
    limit?: number;
}

export interface UpdateFileApiV1FilesFileIdPutRequest {
    fileId: string;
    fileOrFolderUpdate: FileOrFolderUpdate;
}

export interface UploadFileApiV1FilesFolderIdUploadPostRequest {
    folderId: number;
    file: Blob;
    force?: boolean;
}

/**
 * 
 */
export class FilesApi extends runtime.BaseAPI {

    /**
     * Create a new folder.
     * Create Folder
     */
    async createFolderApiV1FilesFolderIdPostRaw(requestParameters: CreateFolderApiV1FilesFolderIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileOrFolder>> {
        if (requestParameters.folderId === null || requestParameters.folderId === undefined) {
            throw new runtime.RequiredError('folderId','Required parameter requestParameters.folderId was null or undefined when calling createFolderApiV1FilesFolderIdPost.');
        }

        if (requestParameters.folderCreate === null || requestParameters.folderCreate === undefined) {
            throw new runtime.RequiredError('folderCreate','Required parameter requestParameters.folderCreate was null or undefined when calling createFolderApiV1FilesFolderIdPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2AuthorizationCodeBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/files/{folder_id}`.replace(`{${"folder_id"}}`, encodeURIComponent(String(requestParameters.folderId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FolderCreateToJSON(requestParameters.folderCreate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileOrFolderFromJSON(jsonValue));
    }

    /**
     * Create a new folder.
     * Create Folder
     */
    async createFolderApiV1FilesFolderIdPost(requestParameters: CreateFolderApiV1FilesFolderIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileOrFolder> {
        const response = await this.createFolderApiV1FilesFolderIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an existing file or folder.
     * Delete File
     */
    async deleteFileApiV1FilesFileIdDeleteRaw(requestParameters: DeleteFileApiV1FilesFileIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.fileId === null || requestParameters.fileId === undefined) {
            throw new runtime.RequiredError('fileId','Required parameter requestParameters.fileId was null or undefined when calling deleteFileApiV1FilesFileIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2AuthorizationCodeBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/files/{file_id}`.replace(`{${"file_id"}}`, encodeURIComponent(String(requestParameters.fileId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an existing file or folder.
     * Delete File
     */
    async deleteFileApiV1FilesFileIdDelete(requestParameters: DeleteFileApiV1FilesFileIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteFileApiV1FilesFileIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get breadcrumb for a file.
     * Get Breadcrumb
     */
    async getBreadcrumbApiV1FilesFileIdBreadcrumbGetRaw(requestParameters: GetBreadcrumbApiV1FilesFileIdBreadcrumbGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FileOrFolder>>> {
        if (requestParameters.fileId === null || requestParameters.fileId === undefined) {
            throw new runtime.RequiredError('fileId','Required parameter requestParameters.fileId was null or undefined when calling getBreadcrumbApiV1FilesFileIdBreadcrumbGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2AuthorizationCodeBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/files/{file_id}/breadcrumb`.replace(`{${"file_id"}}`, encodeURIComponent(String(requestParameters.fileId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FileOrFolderFromJSON));
    }

    /**
     * Get breadcrumb for a file.
     * Get Breadcrumb
     */
    async getBreadcrumbApiV1FilesFileIdBreadcrumbGet(requestParameters: GetBreadcrumbApiV1FilesFileIdBreadcrumbGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FileOrFolder>> {
        const response = await this.getBreadcrumbApiV1FilesFileIdBreadcrumbGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a file or folder by id.
     * Get File
     */
    async getFileApiV1FilesFileIdGetRaw(requestParameters: GetFileApiV1FilesFileIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileOrFolder>> {
        if (requestParameters.fileId === null || requestParameters.fileId === undefined) {
            throw new runtime.RequiredError('fileId','Required parameter requestParameters.fileId was null or undefined when calling getFileApiV1FilesFileIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2AuthorizationCodeBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/files/{file_id}`.replace(`{${"file_id"}}`, encodeURIComponent(String(requestParameters.fileId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileOrFolderFromJSON(jsonValue));
    }

    /**
     * Get a file or folder by id.
     * Get File
     */
    async getFileApiV1FilesFileIdGet(requestParameters: GetFileApiV1FilesFileIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileOrFolder> {
        const response = await this.getFileApiV1FilesFileIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get root folder entity.
     * Get Root
     */
    async getRootApiV1FilesRootGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileOrFolder>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2AuthorizationCodeBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/files/root`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileOrFolderFromJSON(jsonValue));
    }

    /**
     * Get root folder entity.
     * Get Root
     */
    async getRootApiV1FilesRootGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileOrFolder> {
        const response = await this.getRootApiV1FilesRootGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get all chidren of a folder.
     * List Children
     */
    async listChildrenApiV1FilesFolderIdChildrenGetRaw(requestParameters: ListChildrenApiV1FilesFolderIdChildrenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FileOrFolder>>> {
        if (requestParameters.folderId === null || requestParameters.folderId === undefined) {
            throw new runtime.RequiredError('folderId','Required parameter requestParameters.folderId was null or undefined when calling listChildrenApiV1FilesFolderIdChildrenGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2AuthorizationCodeBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/files/{folder_id}/children`.replace(`{${"folder_id"}}`, encodeURIComponent(String(requestParameters.folderId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FileOrFolderFromJSON));
    }

    /**
     * Get all chidren of a folder.
     * List Children
     */
    async listChildrenApiV1FilesFolderIdChildrenGet(requestParameters: ListChildrenApiV1FilesFolderIdChildrenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FileOrFolder>> {
        const response = await this.listChildrenApiV1FilesFolderIdChildrenGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List recent files.
     * List Files
     */
    async listFilesApiV1FilesGetRaw(requestParameters: ListFilesApiV1FilesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FileOrFolder>>> {
        const queryParameters: any = {};

        if (requestParameters.t !== undefined) {
            queryParameters['t'] = requestParameters.t;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2AuthorizationCodeBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/files/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FileOrFolderFromJSON));
    }

    /**
     * List recent files.
     * List Files
     */
    async listFilesApiV1FilesGet(requestParameters: ListFilesApiV1FilesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FileOrFolder>> {
        const response = await this.listFilesApiV1FilesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing file or folder
     * Update File
     */
    async updateFileApiV1FilesFileIdPutRaw(requestParameters: UpdateFileApiV1FilesFileIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileOrFolder>> {
        if (requestParameters.fileId === null || requestParameters.fileId === undefined) {
            throw new runtime.RequiredError('fileId','Required parameter requestParameters.fileId was null or undefined when calling updateFileApiV1FilesFileIdPut.');
        }

        if (requestParameters.fileOrFolderUpdate === null || requestParameters.fileOrFolderUpdate === undefined) {
            throw new runtime.RequiredError('fileOrFolderUpdate','Required parameter requestParameters.fileOrFolderUpdate was null or undefined when calling updateFileApiV1FilesFileIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2AuthorizationCodeBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/files/{file_id}`.replace(`{${"file_id"}}`, encodeURIComponent(String(requestParameters.fileId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: FileOrFolderUpdateToJSON(requestParameters.fileOrFolderUpdate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileOrFolderFromJSON(jsonValue));
    }

    /**
     * Update an existing file or folder
     * Update File
     */
    async updateFileApiV1FilesFileIdPut(requestParameters: UpdateFileApiV1FilesFileIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileOrFolder> {
        const response = await this.updateFileApiV1FilesFileIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload a file.
     * Upload File
     */
    async uploadFileApiV1FilesFolderIdUploadPostRaw(requestParameters: UploadFileApiV1FilesFolderIdUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileOrFolder>> {
        if (requestParameters.folderId === null || requestParameters.folderId === undefined) {
            throw new runtime.RequiredError('folderId','Required parameter requestParameters.folderId was null or undefined when calling uploadFileApiV1FilesFolderIdUploadPost.');
        }

        if (requestParameters.file === null || requestParameters.file === undefined) {
            throw new runtime.RequiredError('file','Required parameter requestParameters.file was null or undefined when calling uploadFileApiV1FilesFolderIdUploadPost.');
        }

        const queryParameters: any = {};

        if (requestParameters.force !== undefined) {
            queryParameters['force'] = requestParameters.force;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2AuthorizationCodeBearer", []);
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.file !== undefined) {
            formParams.append('file', requestParameters.file as any);
        }

        const response = await this.request({
            path: `/api/v1/files/{folder_id}/upload`.replace(`{${"folder_id"}}`, encodeURIComponent(String(requestParameters.folderId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileOrFolderFromJSON(jsonValue));
    }

    /**
     * Upload a file.
     * Upload File
     */
    async uploadFileApiV1FilesFolderIdUploadPost(requestParameters: UploadFileApiV1FilesFolderIdUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileOrFolder> {
        const response = await this.uploadFileApiV1FilesFolderIdUploadPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
