/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type MembershipLinkRequest,
    MembershipLinkRequestFromJSON,
    MembershipLinkRequestToJSON,
} from '../models/MembershipLinkRequest';
import {
    type UnlinkedMembership,
    UnlinkedMembershipFromJSON,
    UnlinkedMembershipToJSON,
} from '../models/UnlinkedMembership';

export interface DeleteMembershipApiV1HelloassoOrdersMembershipIdDeleteRequest {
    /**
     * 
     */
    membershipId: string;
}

export interface HelloassoWebhookApiV1HelloassoWebhookPostRequest {
    /**
     * 
     */
    token?: string | null;
    /**
     * 
     */
    xHaSignature?: string | null;
}

export interface LinkMembershipApiV1HelloassoOrdersMembershipIdLinkPostRequest {
    /**
     * 
     */
    membershipId: string;
    /**
     * 
     */
    membershipLinkRequest: MembershipLinkRequest;
}

/**
 * 
 */
export class HelloAssoApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteMembershipApiV1HelloassoOrdersMembershipIdDelete without sending the request
     */
    async deleteMembershipApiV1HelloassoOrdersMembershipIdDeleteRequestOpts(requestParameters: DeleteMembershipApiV1HelloassoOrdersMembershipIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['membershipId'] == null) {
            throw new runtime.RequiredError(
                'membershipId',
                'Required parameter "membershipId" was null or undefined when calling deleteMembershipApiV1HelloassoOrdersMembershipIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/helloasso/orders/{membership_id}`;
        urlPath = urlPath.replace('{membership_id}', encodeURIComponent(String(requestParameters['membershipId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a membership record (e.g. a duplicate or erroneous order).
     * Delete Membership
     */
    async deleteMembershipApiV1HelloassoOrdersMembershipIdDeleteRaw(requestParameters: DeleteMembershipApiV1HelloassoOrdersMembershipIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteMembershipApiV1HelloassoOrdersMembershipIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a membership record (e.g. a duplicate or erroneous order).
     * Delete Membership
     */
    async deleteMembershipApiV1HelloassoOrdersMembershipIdDelete(requestParameters: DeleteMembershipApiV1HelloassoOrdersMembershipIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteMembershipApiV1HelloassoOrdersMembershipIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for helloassoWebhookApiV1HelloassoWebhookPost without sending the request
     */
    async helloassoWebhookApiV1HelloassoWebhookPostRequestOpts(requestParameters: HelloassoWebhookApiV1HelloassoWebhookPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xHaSignature'] != null) {
            headerParameters['x-ha-signature'] = String(requestParameters['xHaSignature']);
        }


        let urlPath = `/api/v1/helloasso/webhook`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Receive a HelloAsso notification and persist membership items.  Always returns 200 for authentic, well-formed notifications (even when there is nothing to store), because any non-200 makes HelloAsso retry the delivery for up to 27 hours.
     * Helloasso Webhook
     */
    async helloassoWebhookApiV1HelloassoWebhookPostRaw(requestParameters: HelloassoWebhookApiV1HelloassoWebhookPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.helloassoWebhookApiV1HelloassoWebhookPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Receive a HelloAsso notification and persist membership items.  Always returns 200 for authentic, well-formed notifications (even when there is nothing to store), because any non-200 makes HelloAsso retry the delivery for up to 27 hours.
     * Helloasso Webhook
     */
    async helloassoWebhookApiV1HelloassoWebhookPost(requestParameters: HelloassoWebhookApiV1HelloassoWebhookPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.helloassoWebhookApiV1HelloassoWebhookPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for linkMembershipApiV1HelloassoOrdersMembershipIdLinkPost without sending the request
     */
    async linkMembershipApiV1HelloassoOrdersMembershipIdLinkPostRequestOpts(requestParameters: LinkMembershipApiV1HelloassoOrdersMembershipIdLinkPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['membershipId'] == null) {
            throw new runtime.RequiredError(
                'membershipId',
                'Required parameter "membershipId" was null or undefined when calling linkMembershipApiV1HelloassoOrdersMembershipIdLinkPost().'
            );
        }

        if (requestParameters['membershipLinkRequest'] == null) {
            throw new runtime.RequiredError(
                'membershipLinkRequest',
                'Required parameter "membershipLinkRequest" was null or undefined when calling linkMembershipApiV1HelloassoOrdersMembershipIdLinkPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/helloasso/orders/{membership_id}/link`;
        urlPath = urlPath.replace('{membership_id}', encodeURIComponent(String(requestParameters['membershipId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MembershipLinkRequestToJSON(requestParameters['membershipLinkRequest']),
        };
    }

    /**
     * Attach an unlinked membership row to a member.
     * Link Membership
     */
    async linkMembershipApiV1HelloassoOrdersMembershipIdLinkPostRaw(requestParameters: LinkMembershipApiV1HelloassoOrdersMembershipIdLinkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UnlinkedMembership>> {
        const requestOptions = await this.linkMembershipApiV1HelloassoOrdersMembershipIdLinkPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UnlinkedMembershipFromJSON(jsonValue));
    }

    /**
     * Attach an unlinked membership row to a member.
     * Link Membership
     */
    async linkMembershipApiV1HelloassoOrdersMembershipIdLinkPost(requestParameters: LinkMembershipApiV1HelloassoOrdersMembershipIdLinkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UnlinkedMembership> {
        const response = await this.linkMembershipApiV1HelloassoOrdersMembershipIdLinkPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listUnlinkedMembershipsApiV1HelloassoOrdersUnlinkedGet without sending the request
     */
    async listUnlinkedMembershipsApiV1HelloassoOrdersUnlinkedGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/helloasso/orders/unlinked`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List membership rows not yet attached to a member (admin reconciliation).
     * List Unlinked Memberships
     */
    async listUnlinkedMembershipsApiV1HelloassoOrdersUnlinkedGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UnlinkedMembership>>> {
        const requestOptions = await this.listUnlinkedMembershipsApiV1HelloassoOrdersUnlinkedGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UnlinkedMembershipFromJSON));
    }

    /**
     * List membership rows not yet attached to a member (admin reconciliation).
     * List Unlinked Memberships
     */
    async listUnlinkedMembershipsApiV1HelloassoOrdersUnlinkedGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UnlinkedMembership>> {
        const response = await this.listUnlinkedMembershipsApiV1HelloassoOrdersUnlinkedGetRaw(initOverrides);
        return await response.value();
    }

}
