/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  MembershipLinkRequest,
  UnlinkedMembership,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MembershipLinkRequestFromJSON,
    MembershipLinkRequestToJSON,
    UnlinkedMembershipFromJSON,
    UnlinkedMembershipToJSON,
} from '../models/index';

export interface DeleteMembershipApiV1HelloassoOrdersMembershipIdDeleteRequest {
    membershipId: string;
}

export interface HelloassoWebhookApiV1HelloassoWebhookPostRequest {
    token?: string | null;
    xHaSignature?: string | null;
}

export interface LinkMembershipApiV1HelloassoOrdersMembershipIdLinkPostRequest {
    membershipId: string;
    membershipLinkRequest: MembershipLinkRequest;
}

/**
 * 
 */
export class HelloAssoApi extends runtime.BaseAPI {

    /**
     * Delete a membership record (e.g. a duplicate or erroneous order).
     * Delete Membership
     */
    async deleteMembershipApiV1HelloassoOrdersMembershipIdDeleteRaw(requestParameters: DeleteMembershipApiV1HelloassoOrdersMembershipIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['membershipId'] == null) {
            throw new runtime.RequiredError(
                'membershipId',
                'Required parameter "membershipId" was null or undefined when calling deleteMembershipApiV1HelloassoOrdersMembershipIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/helloasso/orders/{membership_id}`.replace(`{${"membership_id"}}`, encodeURIComponent(String(requestParameters['membershipId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a membership record (e.g. a duplicate or erroneous order).
     * Delete Membership
     */
    async deleteMembershipApiV1HelloassoOrdersMembershipIdDelete(requestParameters: DeleteMembershipApiV1HelloassoOrdersMembershipIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteMembershipApiV1HelloassoOrdersMembershipIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Receive a HelloAsso notification and persist membership items.  Always returns 200 for authentic, well-formed notifications (even when there is nothing to store), because any non-200 makes HelloAsso retry the delivery for up to 27 hours.
     * Helloasso Webhook
     */
    async helloassoWebhookApiV1HelloassoWebhookPostRaw(requestParameters: HelloassoWebhookApiV1HelloassoWebhookPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xHaSignature'] != null) {
            headerParameters['x-ha-signature'] = String(requestParameters['xHaSignature']);
        }

        const response = await this.request({
            path: `/api/v1/helloasso/webhook`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Receive a HelloAsso notification and persist membership items.  Always returns 200 for authentic, well-formed notifications (even when there is nothing to store), because any non-200 makes HelloAsso retry the delivery for up to 27 hours.
     * Helloasso Webhook
     */
    async helloassoWebhookApiV1HelloassoWebhookPost(requestParameters: HelloassoWebhookApiV1HelloassoWebhookPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.helloassoWebhookApiV1HelloassoWebhookPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Attach an unlinked membership row to a member.
     * Link Membership
     */
    async linkMembershipApiV1HelloassoOrdersMembershipIdLinkPostRaw(requestParameters: LinkMembershipApiV1HelloassoOrdersMembershipIdLinkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UnlinkedMembership>> {
        if (requestParameters['membershipId'] == null) {
            throw new runtime.RequiredError(
                'membershipId',
                'Required parameter "membershipId" was null or undefined when calling linkMembershipApiV1HelloassoOrdersMembershipIdLinkPost().'
            );
        }

        if (requestParameters['membershipLinkRequest'] == null) {
            throw new runtime.RequiredError(
                'membershipLinkRequest',
                'Required parameter "membershipLinkRequest" was null or undefined when calling linkMembershipApiV1HelloassoOrdersMembershipIdLinkPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/helloasso/orders/{membership_id}/link`.replace(`{${"membership_id"}}`, encodeURIComponent(String(requestParameters['membershipId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MembershipLinkRequestToJSON(requestParameters['membershipLinkRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UnlinkedMembershipFromJSON(jsonValue));
    }

    /**
     * Attach an unlinked membership row to a member.
     * Link Membership
     */
    async linkMembershipApiV1HelloassoOrdersMembershipIdLinkPost(requestParameters: LinkMembershipApiV1HelloassoOrdersMembershipIdLinkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UnlinkedMembership> {
        const response = await this.linkMembershipApiV1HelloassoOrdersMembershipIdLinkPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List membership rows not yet attached to a member (admin reconciliation).
     * List Unlinked Memberships
     */
    async listUnlinkedMembershipsApiV1HelloassoOrdersUnlinkedGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UnlinkedMembership>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/helloasso/orders/unlinked`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UnlinkedMembershipFromJSON));
    }

    /**
     * List membership rows not yet attached to a member (admin reconciliation).
     * List Unlinked Memberships
     */
    async listUnlinkedMembershipsApiV1HelloassoOrdersUnlinkedGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UnlinkedMembership>> {
        const response = await this.listUnlinkedMembershipsApiV1HelloassoOrdersUnlinkedGetRaw(initOverrides);
        return await response.value();
    }

}
