/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  InvitationAccept,
  InvitationCreate,
  InvitationCreated,
  InvitationInfo,
  OtpRequest,
  Token,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    InvitationAcceptFromJSON,
    InvitationAcceptToJSON,
    InvitationCreateFromJSON,
    InvitationCreateToJSON,
    InvitationCreatedFromJSON,
    InvitationCreatedToJSON,
    InvitationInfoFromJSON,
    InvitationInfoToJSON,
    OtpRequestFromJSON,
    OtpRequestToJSON,
    TokenFromJSON,
    TokenToJSON,
} from '../models/index';

export interface AcceptInvitationApiV1InvitationsTokenAcceptPostRequest {
    token: string;
    invitationAccept: InvitationAccept;
}

export interface CreateInvitationApiV1InvitationsPostRequest {
    invitationCreate: InvitationCreate;
}

export interface GetInvitationApiV1InvitationsTokenGetRequest {
    token: string;
}

export interface RequestOtpApiV1InvitationsTokenOtpPostRequest {
    token: string;
    otpRequest: OtpRequest;
}

/**
 * 
 */
export class InvitationsApi extends runtime.BaseAPI {

    /**
     * Public: create the member account from the invitation and sign them in.  OTP is required unless the invitation email was backend-proven and the submitted email is unchanged. The account is created with default groups only (no privileged roles). On success the new member is signed in as an *additive* browser session (multi-account): their session cookie is set and they become the active account, without logging out anyone already signed in (e.g. a parent inviting a child on the same device). No password is set and no email is sent — the account is passkey-first.
     * Accept Invitation
     */
    async acceptInvitationApiV1InvitationsTokenAcceptPostRaw(requestParameters: AcceptInvitationApiV1InvitationsTokenAcceptPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling acceptInvitationApiV1InvitationsTokenAcceptPost().'
            );
        }

        if (requestParameters['invitationAccept'] == null) {
            throw new runtime.RequiredError(
                'invitationAccept',
                'Required parameter "invitationAccept" was null or undefined when calling acceptInvitationApiV1InvitationsTokenAcceptPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/invitations/{token}/accept`.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InvitationAcceptToJSON(requestParameters['invitationAccept']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
    }

    /**
     * Public: create the member account from the invitation and sign them in.  OTP is required unless the invitation email was backend-proven and the submitted email is unchanged. The account is created with default groups only (no privileged roles). On success the new member is signed in as an *additive* browser session (multi-account): their session cookie is set and they become the active account, without logging out anyone already signed in (e.g. a parent inviting a child on the same device). No password is set and no email is sent — the account is passkey-first.
     * Accept Invitation
     */
    async acceptInvitationApiV1InvitationsTokenAcceptPost(requestParameters: AcceptInvitationApiV1InvitationsTokenAcceptPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token> {
        const response = await this.acceptInvitationApiV1InvitationsTokenAcceptPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate an invitation and (for the email channel) send it.
     * Create Invitation
     */
    async createInvitationApiV1InvitationsPostRaw(requestParameters: CreateInvitationApiV1InvitationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvitationCreated>> {
        if (requestParameters['invitationCreate'] == null) {
            throw new runtime.RequiredError(
                'invitationCreate',
                'Required parameter "invitationCreate" was null or undefined when calling createInvitationApiV1InvitationsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/invitations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InvitationCreateToJSON(requestParameters['invitationCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvitationCreatedFromJSON(jsonValue));
    }

    /**
     * Generate an invitation and (for the email channel) send it.
     * Create Invitation
     */
    async createInvitationApiV1InvitationsPost(requestParameters: CreateInvitationApiV1InvitationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvitationCreated> {
        const response = await this.createInvitationApiV1InvitationsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Public: return prefill data for the signup form (does not consume).
     * Get Invitation
     */
    async getInvitationApiV1InvitationsTokenGetRaw(requestParameters: GetInvitationApiV1InvitationsTokenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvitationInfo>> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling getInvitationApiV1InvitationsTokenGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/invitations/{token}`.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvitationInfoFromJSON(jsonValue));
    }

    /**
     * Public: return prefill data for the signup form (does not consume).
     * Get Invitation
     */
    async getInvitationApiV1InvitationsTokenGet(requestParameters: GetInvitationApiV1InvitationsTokenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvitationInfo> {
        const response = await this.getInvitationApiV1InvitationsTokenGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Public: send a one-time code to the address the invitee entered.  A fresh OTP token supersedes any previous one for this invitation, so only the latest code is valid.
     * Request Otp
     */
    async requestOtpApiV1InvitationsTokenOtpPostRaw(requestParameters: RequestOtpApiV1InvitationsTokenOtpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling requestOtpApiV1InvitationsTokenOtpPost().'
            );
        }

        if (requestParameters['otpRequest'] == null) {
            throw new runtime.RequiredError(
                'otpRequest',
                'Required parameter "otpRequest" was null or undefined when calling requestOtpApiV1InvitationsTokenOtpPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/invitations/{token}/otp`.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OtpRequestToJSON(requestParameters['otpRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Public: send a one-time code to the address the invitee entered.  A fresh OTP token supersedes any previous one for this invitation, so only the latest code is valid.
     * Request Otp
     */
    async requestOtpApiV1InvitationsTokenOtpPost(requestParameters: RequestOtpApiV1InvitationsTokenOtpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.requestOtpApiV1InvitationsTokenOtpPostRaw(requestParameters, initOverrides);
    }

}
