/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type InvitationAccept,
    InvitationAcceptFromJSON,
    InvitationAcceptToJSON,
} from '../models/InvitationAccept';
import {
    type InvitationCreate,
    InvitationCreateFromJSON,
    InvitationCreateToJSON,
} from '../models/InvitationCreate';
import {
    type InvitationCreated,
    InvitationCreatedFromJSON,
    InvitationCreatedToJSON,
} from '../models/InvitationCreated';
import {
    type InvitationInfo,
    InvitationInfoFromJSON,
    InvitationInfoToJSON,
} from '../models/InvitationInfo';
import {
    type OtpRequest,
    OtpRequestFromJSON,
    OtpRequestToJSON,
} from '../models/OtpRequest';
import {
    type Token,
    TokenFromJSON,
    TokenToJSON,
} from '../models/Token';

export interface AcceptInvitationApiV1InvitationsTokenAcceptPostRequest {
    /**
     * 
     */
    token: string;
    /**
     * 
     */
    invitationAccept: InvitationAccept;
}

export interface CreateInvitationApiV1InvitationsPostRequest {
    /**
     * 
     */
    invitationCreate: InvitationCreate;
}

export interface GetInvitationApiV1InvitationsTokenGetRequest {
    /**
     * 
     */
    token: string;
}

export interface RequestOtpApiV1InvitationsTokenOtpPostRequest {
    /**
     * 
     */
    token: string;
    /**
     * 
     */
    otpRequest: OtpRequest;
}

/**
 * 
 */
export class InvitationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for acceptInvitationApiV1InvitationsTokenAcceptPost without sending the request
     */
    async acceptInvitationApiV1InvitationsTokenAcceptPostRequestOpts(requestParameters: AcceptInvitationApiV1InvitationsTokenAcceptPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling acceptInvitationApiV1InvitationsTokenAcceptPost().'
            );
        }

        if (requestParameters['invitationAccept'] == null) {
            throw new runtime.RequiredError(
                'invitationAccept',
                'Required parameter "invitationAccept" was null or undefined when calling acceptInvitationApiV1InvitationsTokenAcceptPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/invitations/{token}/accept`;
        urlPath = urlPath.replace('{token}', encodeURIComponent(String(requestParameters['token'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InvitationAcceptToJSON(requestParameters['invitationAccept']),
        };
    }

    /**
     * Public: create the member account from the invitation and sign them in.  OTP is required unless the invitation email was backend-proven and the submitted email is unchanged. The account gets its instrument plus the default groups only (never a privileged role). On success the new member is signed in as an *additive* multi-account session (no other account is logged out) and becomes the active account - no password is set and no email is sent, the account is passkey-first.
     * Accept Invitation
     */
    async acceptInvitationApiV1InvitationsTokenAcceptPostRaw(requestParameters: AcceptInvitationApiV1InvitationsTokenAcceptPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>> {
        const requestOptions = await this.acceptInvitationApiV1InvitationsTokenAcceptPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
    }

    /**
     * Public: create the member account from the invitation and sign them in.  OTP is required unless the invitation email was backend-proven and the submitted email is unchanged. The account gets its instrument plus the default groups only (never a privileged role). On success the new member is signed in as an *additive* multi-account session (no other account is logged out) and becomes the active account - no password is set and no email is sent, the account is passkey-first.
     * Accept Invitation
     */
    async acceptInvitationApiV1InvitationsTokenAcceptPost(requestParameters: AcceptInvitationApiV1InvitationsTokenAcceptPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token> {
        const response = await this.acceptInvitationApiV1InvitationsTokenAcceptPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createInvitationApiV1InvitationsPost without sending the request
     */
    async createInvitationApiV1InvitationsPostRequestOpts(requestParameters: CreateInvitationApiV1InvitationsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['invitationCreate'] == null) {
            throw new runtime.RequiredError(
                'invitationCreate',
                'Required parameter "invitationCreate" was null or undefined when calling createInvitationApiV1InvitationsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/invitations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InvitationCreateToJSON(requestParameters['invitationCreate']),
        };
    }

    /**
     * Generate an invitation and (for the email channel) send it.
     * Create Invitation
     */
    async createInvitationApiV1InvitationsPostRaw(requestParameters: CreateInvitationApiV1InvitationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvitationCreated>> {
        const requestOptions = await this.createInvitationApiV1InvitationsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvitationCreatedFromJSON(jsonValue));
    }

    /**
     * Generate an invitation and (for the email channel) send it.
     * Create Invitation
     */
    async createInvitationApiV1InvitationsPost(requestParameters: CreateInvitationApiV1InvitationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvitationCreated> {
        const response = await this.createInvitationApiV1InvitationsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getInvitationApiV1InvitationsTokenGet without sending the request
     */
    async getInvitationApiV1InvitationsTokenGetRequestOpts(requestParameters: GetInvitationApiV1InvitationsTokenGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling getInvitationApiV1InvitationsTokenGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/invitations/{token}`;
        urlPath = urlPath.replace('{token}', encodeURIComponent(String(requestParameters['token'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Public: return prefill data for the signup form (does not consume).
     * Get Invitation
     */
    async getInvitationApiV1InvitationsTokenGetRaw(requestParameters: GetInvitationApiV1InvitationsTokenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvitationInfo>> {
        const requestOptions = await this.getInvitationApiV1InvitationsTokenGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvitationInfoFromJSON(jsonValue));
    }

    /**
     * Public: return prefill data for the signup form (does not consume).
     * Get Invitation
     */
    async getInvitationApiV1InvitationsTokenGet(requestParameters: GetInvitationApiV1InvitationsTokenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvitationInfo> {
        const response = await this.getInvitationApiV1InvitationsTokenGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for requestOtpApiV1InvitationsTokenOtpPost without sending the request
     */
    async requestOtpApiV1InvitationsTokenOtpPostRequestOpts(requestParameters: RequestOtpApiV1InvitationsTokenOtpPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling requestOtpApiV1InvitationsTokenOtpPost().'
            );
        }

        if (requestParameters['otpRequest'] == null) {
            throw new runtime.RequiredError(
                'otpRequest',
                'Required parameter "otpRequest" was null or undefined when calling requestOtpApiV1InvitationsTokenOtpPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/invitations/{token}/otp`;
        urlPath = urlPath.replace('{token}', encodeURIComponent(String(requestParameters['token'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OtpRequestToJSON(requestParameters['otpRequest']),
        };
    }

    /**
     * Public: send a one-time code to the address the invitee entered.  A fresh code supersedes any previous one for this invitation, so only the latest is valid.
     * Request Otp
     */
    async requestOtpApiV1InvitationsTokenOtpPostRaw(requestParameters: RequestOtpApiV1InvitationsTokenOtpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.requestOtpApiV1InvitationsTokenOtpPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Public: send a one-time code to the address the invitee entered.  A fresh code supersedes any previous one for this invitation, so only the latest is valid.
     * Request Otp
     */
    async requestOtpApiV1InvitationsTokenOtpPost(requestParameters: RequestOtpApiV1InvitationsTokenOtpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.requestOtpApiV1InvitationsTokenOtpPostRaw(requestParameters, initOverrides);
    }

}
