/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetUploadUrlResponse,
  GlobalStats,
  Group,
  GroupCreate,
  GroupUpdate,
  HTTPValidationError,
  MyProfileUpdate,
  MyStats,
  Permission,
  Profile,
  ProfileCreate,
  ProfileUpdate,
} from '../models/index';
import {
    GetUploadUrlResponseFromJSON,
    GetUploadUrlResponseToJSON,
    GlobalStatsFromJSON,
    GlobalStatsToJSON,
    GroupFromJSON,
    GroupToJSON,
    GroupCreateFromJSON,
    GroupCreateToJSON,
    GroupUpdateFromJSON,
    GroupUpdateToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MyProfileUpdateFromJSON,
    MyProfileUpdateToJSON,
    MyStatsFromJSON,
    MyStatsToJSON,
    PermissionFromJSON,
    PermissionToJSON,
    ProfileFromJSON,
    ProfileToJSON,
    ProfileCreateFromJSON,
    ProfileCreateToJSON,
    ProfileUpdateFromJSON,
    ProfileUpdateToJSON,
} from '../models/index';

export interface CreateGroupApiV1GroupsPostRequest {
    groupCreate: GroupCreate;
}

export interface CreateProfileApiV1ProfilesPostRequest {
    profileCreate: ProfileCreate;
}

export interface GetGroupApiV1GroupsGroupIdGetRequest {
    groupId: number;
}

export interface GetProfileApiV1ProfilesProfileIdGetRequest {
    profileId: string;
}

export interface UpdateGroupApiV1GroupsGroupIdPutRequest {
    groupId: number;
    groupUpdate: GroupUpdate;
}

export interface UpdateMyProfileApiV1ProfilesMePutRequest {
    myProfileUpdate: MyProfileUpdate;
}

export interface UpdateProfileApiV1ProfilesProfileIdPutRequest {
    profileId: string;
    profileUpdate: ProfileUpdate;
}

/**
 * 
 */
export class ProfilesApi extends runtime.BaseAPI {

    /**
     * Create Group
     */
    async createGroupApiV1GroupsPostRaw(requestParameters: CreateGroupApiV1GroupsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Group>> {
        if (requestParameters['groupCreate'] == null) {
            throw new runtime.RequiredError(
                'groupCreate',
                'Required parameter "groupCreate" was null or undefined when calling createGroupApiV1GroupsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/groups/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GroupCreateToJSON(requestParameters['groupCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupFromJSON(jsonValue));
    }

    /**
     * Create Group
     */
    async createGroupApiV1GroupsPost(requestParameters: CreateGroupApiV1GroupsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Group> {
        const response = await this.createGroupApiV1GroupsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Profile
     */
    async createProfileApiV1ProfilesPostRaw(requestParameters: CreateProfileApiV1ProfilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Profile>>> {
        if (requestParameters['profileCreate'] == null) {
            throw new runtime.RequiredError(
                'profileCreate',
                'Required parameter "profileCreate" was null or undefined when calling createProfileApiV1ProfilesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/profiles/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProfileCreateToJSON(requestParameters['profileCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProfileFromJSON));
    }

    /**
     * Create Profile
     */
    async createProfileApiV1ProfilesPost(requestParameters: CreateProfileApiV1ProfilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Profile>> {
        const response = await this.createProfileApiV1ProfilesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Global Stats
     */
    async getGlobalStatsApiV1StatsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GlobalStats>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/stats/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GlobalStatsFromJSON(jsonValue));
    }

    /**
     * Get Global Stats
     */
    async getGlobalStatsApiV1StatsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GlobalStats> {
        const response = await this.getGlobalStatsApiV1StatsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get Group
     */
    async getGroupApiV1GroupsGroupIdGetRaw(requestParameters: GetGroupApiV1GroupsGroupIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Group>> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling getGroupApiV1GroupsGroupIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/groups/{group_id}`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters['groupId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupFromJSON(jsonValue));
    }

    /**
     * Get Group
     */
    async getGroupApiV1GroupsGroupIdGet(requestParameters: GetGroupApiV1GroupsGroupIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Group> {
        const response = await this.getGroupApiV1GroupsGroupIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get My Permissions
     */
    async getMyPermissionsApiV1ProfilesMePermissionsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string | null>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/profiles/me/permissions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get My Permissions
     */
    async getMyPermissionsApiV1ProfilesMePermissionsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string | null>> {
        const response = await this.getMyPermissionsApiV1ProfilesMePermissionsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get My Profile
     */
    async getMyProfileApiV1ProfilesMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Profile>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/profiles/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileFromJSON(jsonValue));
    }

    /**
     * Get My Profile
     */
    async getMyProfileApiV1ProfilesMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Profile> {
        const response = await this.getMyProfileApiV1ProfilesMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get My Stats
     */
    async getMyStatsApiV1StatsMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MyStats>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/stats/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MyStatsFromJSON(jsonValue));
    }

    /**
     * Get My Stats
     */
    async getMyStatsApiV1StatsMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MyStats> {
        const response = await this.getMyStatsApiV1StatsMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get Profile
     */
    async getProfileApiV1ProfilesProfileIdGetRaw(requestParameters: GetProfileApiV1ProfilesProfileIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Profile>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling getProfileApiV1ProfilesProfileIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/profiles/{profile_id}`.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileFromJSON(jsonValue));
    }

    /**
     * Get Profile
     */
    async getProfileApiV1ProfilesProfileIdGet(requestParameters: GetProfileApiV1ProfilesProfileIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Profile> {
        const response = await this.getProfileApiV1ProfilesProfileIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Groups
     */
    async listGroupsApiV1GroupsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Group>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/groups/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GroupFromJSON));
    }

    /**
     * List Groups
     */
    async listGroupsApiV1GroupsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Group>> {
        const response = await this.listGroupsApiV1GroupsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Permissions
     */
    async listPermissionsApiV1PermissionsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Permission>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/permissions/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PermissionFromJSON));
    }

    /**
     * List Permissions
     */
    async listPermissionsApiV1PermissionsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Permission>> {
        const response = await this.listPermissionsApiV1PermissionsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Profiles
     */
    async listProfilesApiV1ProfilesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Profile>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/profiles/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProfileFromJSON));
    }

    /**
     * List Profiles
     */
    async listProfilesApiV1ProfilesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Profile>> {
        const response = await this.listProfilesApiV1ProfilesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update Group
     */
    async updateGroupApiV1GroupsGroupIdPutRaw(requestParameters: UpdateGroupApiV1GroupsGroupIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Group>> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling updateGroupApiV1GroupsGroupIdPut().'
            );
        }

        if (requestParameters['groupUpdate'] == null) {
            throw new runtime.RequiredError(
                'groupUpdate',
                'Required parameter "groupUpdate" was null or undefined when calling updateGroupApiV1GroupsGroupIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/groups/{group_id}`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters['groupId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: GroupUpdateToJSON(requestParameters['groupUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupFromJSON(jsonValue));
    }

    /**
     * Update Group
     */
    async updateGroupApiV1GroupsGroupIdPut(requestParameters: UpdateGroupApiV1GroupsGroupIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Group> {
        const response = await this.updateGroupApiV1GroupsGroupIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update My Profile
     */
    async updateMyProfileApiV1ProfilesMePutRaw(requestParameters: UpdateMyProfileApiV1ProfilesMePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Profile>> {
        if (requestParameters['myProfileUpdate'] == null) {
            throw new runtime.RequiredError(
                'myProfileUpdate',
                'Required parameter "myProfileUpdate" was null or undefined when calling updateMyProfileApiV1ProfilesMePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/profiles/me`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MyProfileUpdateToJSON(requestParameters['myProfileUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileFromJSON(jsonValue));
    }

    /**
     * Update My Profile
     */
    async updateMyProfileApiV1ProfilesMePut(requestParameters: UpdateMyProfileApiV1ProfilesMePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Profile> {
        const response = await this.updateMyProfileApiV1ProfilesMePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Profile
     */
    async updateProfileApiV1ProfilesProfileIdPutRaw(requestParameters: UpdateProfileApiV1ProfilesProfileIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Profile>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling updateProfileApiV1ProfilesProfileIdPut().'
            );
        }

        if (requestParameters['profileUpdate'] == null) {
            throw new runtime.RequiredError(
                'profileUpdate',
                'Required parameter "profileUpdate" was null or undefined when calling updateProfileApiV1ProfilesProfileIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/profiles/{profile_id}`.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProfileUpdateToJSON(requestParameters['profileUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileFromJSON(jsonValue));
    }

    /**
     * Update Profile
     */
    async updateProfileApiV1ProfilesProfileIdPut(requestParameters: UpdateProfileApiV1ProfilesProfileIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Profile> {
        const response = await this.updateProfileApiV1ProfilesProfileIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload Avatar
     */
    async uploadAvatarApiV1ProfilesMeAvatarPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUploadUrlResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/profiles/me/avatar`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUploadUrlResponseFromJSON(jsonValue));
    }

    /**
     * Upload Avatar
     */
    async uploadAvatarApiV1ProfilesMeAvatarPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUploadUrlResponse> {
        const response = await this.uploadAvatarApiV1ProfilesMeAvatarPostRaw(initOverrides);
        return await response.value();
    }

}
