/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  PushSubscriptionCreate,
  PushSubscriptionResponse,
  VapidPublicKeyResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PushSubscriptionCreateFromJSON,
    PushSubscriptionCreateToJSON,
    PushSubscriptionResponseFromJSON,
    PushSubscriptionResponseToJSON,
    VapidPublicKeyResponseFromJSON,
    VapidPublicKeyResponseToJSON,
} from '../models/index';

export interface SubscribeApiV1PushSubscribePostRequest {
    pushSubscriptionCreate: PushSubscriptionCreate;
}

export interface UnsubscribeApiV1PushUnsubscribeDeleteRequest {
    pushSubscriptionCreate: PushSubscriptionCreate;
}

/**
 * 
 */
export class PushNotificationsApi extends runtime.BaseAPI {

    /**
     * Return the VAPID public key for the frontend to subscribe.
     * Get Vapid Public Key
     */
    async getVapidPublicKeyApiV1PushVapidPublicKeyGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VapidPublicKeyResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/push/vapid-public-key`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VapidPublicKeyResponseFromJSON(jsonValue));
    }

    /**
     * Return the VAPID public key for the frontend to subscribe.
     * Get Vapid Public Key
     */
    async getVapidPublicKeyApiV1PushVapidPublicKeyGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VapidPublicKeyResponse> {
        const response = await this.getVapidPublicKeyApiV1PushVapidPublicKeyGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Register a push subscription for the current user.  A user can have multiple subscriptions (one per device/browser). Each device/browser generates a unique push endpoint URL. If the same endpoint already exists (same browser re-subscribing), we update the keys instead of creating a duplicate.
     * Subscribe
     */
    async subscribeApiV1PushSubscribePostRaw(requestParameters: SubscribeApiV1PushSubscribePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PushSubscriptionResponse>> {
        if (requestParameters['pushSubscriptionCreate'] == null) {
            throw new runtime.RequiredError(
                'pushSubscriptionCreate',
                'Required parameter "pushSubscriptionCreate" was null or undefined when calling subscribeApiV1PushSubscribePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/push/subscribe`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PushSubscriptionCreateToJSON(requestParameters['pushSubscriptionCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PushSubscriptionResponseFromJSON(jsonValue));
    }

    /**
     * Register a push subscription for the current user.  A user can have multiple subscriptions (one per device/browser). Each device/browser generates a unique push endpoint URL. If the same endpoint already exists (same browser re-subscribing), we update the keys instead of creating a duplicate.
     * Subscribe
     */
    async subscribeApiV1PushSubscribePost(requestParameters: SubscribeApiV1PushSubscribePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PushSubscriptionResponse> {
        const response = await this.subscribeApiV1PushSubscribePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Send a test push notification to the current user.
     * Test Push
     */
    async testPushApiV1PushTestPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/push/test`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Send a test push notification to the current user.
     * Test Push
     */
    async testPushApiV1PushTestPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.testPushApiV1PushTestPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Remove a push subscription for the current user.
     * Unsubscribe
     */
    async unsubscribeApiV1PushUnsubscribeDeleteRaw(requestParameters: UnsubscribeApiV1PushUnsubscribeDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pushSubscriptionCreate'] == null) {
            throw new runtime.RequiredError(
                'pushSubscriptionCreate',
                'Required parameter "pushSubscriptionCreate" was null or undefined when calling unsubscribeApiV1PushUnsubscribeDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/push/unsubscribe`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: PushSubscriptionCreateToJSON(requestParameters['pushSubscriptionCreate']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a push subscription for the current user.
     * Unsubscribe
     */
    async unsubscribeApiV1PushUnsubscribeDelete(requestParameters: UnsubscribeApiV1PushUnsubscribeDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.unsubscribeApiV1PushUnsubscribeDeleteRaw(requestParameters, initOverrides);
    }

}
