/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetEmailsApiV1UtilsEmailsGetRequest {
    authorization?: string | null;
    accessToken?: string | null;
}

/**
 * 
 */
export class UtilsApi extends runtime.BaseAPI {

    /**
     * Get Emails
     */
    async getEmailsApiV1UtilsEmailsGetRaw(requestParameters: GetEmailsApiV1UtilsEmailsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/api/v1/utils/emails`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Emails
     */
    async getEmailsApiV1UtilsEmailsGet(requestParameters: GetEmailsApiV1UtilsEmailsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.getEmailsApiV1UtilsEmailsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
