/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InboxEmail,
} from '../models/index';
import {
    InboxEmailFromJSON,
    InboxEmailToJSON,
} from '../models/index';

/**
 * 
 */
export class UtilsApi extends runtime.BaseAPI {

    /**
     * Get Emails
     */
    async getEmailsApiV1UtilsEmailsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InboxEmail>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/utils/emails`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InboxEmailFromJSON));
    }

    /**
     * Get Emails
     */
    async getEmailsApiV1UtilsEmailsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InboxEmail>> {
        const response = await this.getEmailsApiV1UtilsEmailsGetRaw(initOverrides);
        return await response.value();
    }

}
