/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseCreate
 */
export interface ResponseCreate {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseCreate
     */
    value: boolean;
}

/**
 * Check if a given object implements the ResponseCreate interface.
 */
export function instanceOfResponseCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function ResponseCreateFromJSON(json: any): ResponseCreate {
    return ResponseCreateFromJSONTyped(json, false);
}

export function ResponseCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function ResponseCreateToJSON(value?: ResponseCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

