version: '3.8'

services:
  frontend:
    build:
      context: frontend
      target: node-env
    volumes:
      - ./frontend:/project
    ports:
      - 5173:5173
      - 6006:6006
    environment:
      - VITE_BBE2_API_URL=https://api.beta.bagadmenru.bzh
      - VITE_OIDC_PROVIDER_URL=https://auth.beta.bagadmenru.bzh/realms/bagadmenru
      - VITE_OIDC_CLIENT_ID=bbe2-frontend-dev

volumes:
  s3data:
  pgdata:
