version: '3.8'

services:
  storage:
    image: minio/minio
    command: server /data --console-address :9090
    ports:
      - 9090:9090
      - 9000:9000
    volumes:
      - s3data:/data

  db:
    image: postgres:15-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=kcwRzG4coiE

  keycloak:
    build: keycloak
    command: --verbose start-dev --import-realm
    ports:
      - 8080:8080
    volumes:
      - ./realm:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_DB=postgres
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=kcwRzG4coiE
      - KC_DB_URL_HOST=db
      - KC_DB_URL_DATABASE=postgres

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  backend:
    build: backend
    command:  [ "uvicorn", "bbe2.main:app", "--reload", "--reload-dir", "bbe2", "--host", "0.0.0.0" ]
    volumes:
      - ./backend:/project
    ports:
      - 8000:8000
    environment:
      - JWT_AUDIENCE=bbe2
      - JWT_ISSUER=http://localhost:8080/realms/bagadmenru
      - OIDC_AUTHORIZATION_URL=http://localhost:8080/realms/bagadmenru/protocol/openid-connect/auth
      - OIDC_TOKEN_URL=http://keycloak:8080/realms/bagadmenru/protocol/openid-connect/token
      - OIDC_JWKS_URL=http://keycloak:8080/realms/bagadmenru/protocol/openid-connect/certs
      - CORS_ALLOWED_ORIGINS=["http://localhost:5173"]
      # - S3_ENDPOINT=http://storage:9000
      # - S3_BUCKET_NAME=bagadmenru5-dev
      # - S3_ACCESS_KEY_ID=minioadmin
      # - S3_SECRET_ACCESS_KEY=minioadmin

      # - S3_BUCKET_NAME=my-test-bucket-mael
      # - S3_ACCESS_KEY_ID=AKIAYRCG2BYTPHFQWRX6
      # - S3_SECRET_ACCESS_KEY=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

      - S3_ACCESS_KEY_ID=SCWSFP78CDSRDZGESAM2
      - S3_SECRET_ACCESS_KEY=cb1c8794-47b1-476f-af27-c4f6b8e172b7
      - S3_ENDPOINT=https://s3.fr-par.scw.cloud
      - S3_BUCKET_NAME=bagadmenru5-data-staging
      - S3_DEFAULT_REGION=fr-par

      - DATABASE_URL=postgresql+psycopg://postgres:kcwRzG4coiE@db/postgres

  frontend:
    build:
      context: frontend
      target: node-env
    volumes:
      - ./frontend:/project
    ports:
      - 5173:5173
      - 6006:6006
    environment:
      - VITE_BBE2_API_URL=http://localhost:8000
      - VITE_OIDC_PROVIDER_URL=http://localhost:8080/realms/bagadmenru
      - VITE_OIDC_CLIENT_ID=bbe2-frontend

volumes:
  s3data:
  pgdata:
