version: '3.8'

services:

  auth-provider:
    image: ghcr.io/maelgui/bagadmenru-v5/auth-provider
    expose:
      - 3000
    networks:
      - default
      - traefik
    environment:
      - DATABASE_URL=postgresql://bagadmenru:${BACKEND_DATABASE_PASSWORD}@backend-postgres/auth
      - RP_ID=bagadmenru.bzh
      - RP_ORIGIN=https://auth.beta.bagadmenru.bzh
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bagadmenru-auth.rule=Host(`auth.beta.bagadmenru.bzh`)"
      - "traefik.http.routers.bagadmenru-auth.tls.certresolver=myresolver"
    restart: unless-stopped

  backend-postgres:
    image: postgres:15-alpine
    volumes:
      - backend-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=bagadmenru
      - POSTGRES_PASSWORD=${BACKEND_DATABASE_PASSWORD}
    restart: unless-stopped
    networks:
      - default

  backend:
    image: ghcr.io/maelgui/bagadmenru-v5/backend
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql+psycopg://bagadmenru:${BACKEND_DATABASE_PASSWORD}@backend-postgres/bagadmenru
      - DOMAIN=beta.bagadmenru.bzh
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
      - S3_ENDPOINT=https://s3.fr-par.scw.cloud
      - S3_BUCKET_NAME=bagadmenru5-data-staging
      - S3_DEFAULT_REGION=fr-par
      - OIDC_ISSUER=https://auth.beta.bagadmenru.bzh
      - USER_API_ENDPOINT=http://auth-provider:3001/
    restart: unless-stopped
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bagadmenru-backend.rule=Host(`api.beta.bagadmenru.bzh`)"
      - "traefik.http.routers.bagadmenru-backend.tls.certresolver=myresolver"
      - "traefik.http.middlewares.corsheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.corsheader.headers.accesscontrolallowheaders=authorization,content-type"
      - "traefik.http.middlewares.corsheader.headers.accesscontrolalloworiginlist=https://beta.bagadmenru.bzh"
      - "traefik.http.routers.bagadmenru-backend.middlewares=corsheader@docker"

  frontend:
    image: ghcr.io/maelgui/bagadmenru-v5/frontend
    expose:
      - 80
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bagadmenru-frontend.rule=Host(`beta.bagadmenru.bzh`)"
      - "traefik.http.routers.bagadmenru-frontend.tls.certresolver=myresolver"
    restart: unless-stopped

volumes:
  s3data:
  backend-pgdata:


networks:
  traefik:
    external: true
