version: '3.8'

services:
  storage:
    image: minio/minio
    command: server /data --console-address :9090
    ports:
      - 9090:9090
    volumes:
      - s3data:/data

  db:
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=kcwRzG4coiE

  keycloak:
    image: quay.io/keycloak/keycloak
    command: --verbose start --proxy=edge --import-realm --features=account3,declarative-user-profile --hostname-url https://maelgui-expert-sniffle-6vgxqgx97r357p4-8080.preview.app.github.dev/
    ports:
      - 8080:8080
    volumes:
      - ./realm:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=account3,declarative-user-profile
      - KC_HEALTH_ENABLED=true
      - KC_HOSTNAME_ADMIN_URL=https://maelgui-expert-sniffle-6vgxqgx97r357p4-8080.preview.app.github.dev/

  backend:
    build: backend
    volumes:
      - ./backend:/project
    ports:
      - 8000:8000
    environment:
      - JWT_AUDIENCE=bbe2
      - JWT_ISSUER=http://localhost:8080/realms/bagadmenru
      - OIDC_AUTHORIZATION_URL=http://keycloak:8080/realms/bagadmenru/protocol/openid-connect/auth
      - OIDC_TOKEN_URL=http://keycloak:8080/realms/bagadmenru/protocol/openid-connect/token
      - OIDC_JWKS_URL=http://keycloak:8080/realms/bagadmenru/protocol/openid-connect/certs
      - CORS_ALLOWED_ORIGINS=["http://localhost:5173"]
      - S3_ENDPOINT=http://storage
      - S3_ACCESS_KEY_ID=minioadmin
      - S3_SECRET_ACCESS_KEY=minioadmin

  frontend:
    build:
      context: frontend
      target: node-env
    volumes:
      - ./frontend:/project
    ports:
      - 5173:5173
    environment:
      - VITE_BBE2_API_URL=https://maelgui-expert-sniffle-6vgxqgx97r357p4-8000.preview.app.github.dev
      - VITE_OIDC_PROVIDER_URL=https://maelgui-expert-sniffle-6vgxqgx97r357p4-8080.preview.app.github.dev/realms/bagadmenru

volumes:
  s3data:
  pgdata:
