version: '3.8'

services:

  backend-postgres:
    image: postgres:15-alpine
    volumes:
      - backend-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=bagadmenru
      - POSTGRES_PASSWORD=${BACKEND_DATABASE_PASSWORD}
    restart: unless-stopped
    networks:
      - default

  backend-migrate:
    image: ghcr.io/maelgui/bagadmenru-v5/backend:beta
    command: ["alembic", "upgrade", "head"]
    environment:
      - DATABASE_URL=postgresql+psycopg://bagadmenru:${BACKEND_DATABASE_PASSWORD}@backend-postgres/bagadmenru

  backend:
    image: ghcr.io/maelgui/bagadmenru-v5/backend:beta
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql+psycopg://bagadmenru:${BACKEND_DATABASE_PASSWORD}@backend-postgres/bagadmenru
      - DOMAIN=beta.bagadmenru.bzh
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
      - S3_ENDPOINT=https://s3.fr-par.scw.cloud
      - S3_BUCKET_NAME=bagadmenru5-data-staging
      - S3_DEFAULT_REGION=fr-par
      - EMAIL_API_ENDPOINT=http://email-api:9999/
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AUTHORIZER_API_ENDPOINT=http://authorizer:8181/
    restart: unless-stopped
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bagadmenru-backend.rule=Host(`api.beta.bagadmenru.bzh`)"
      - "traefik.http.routers.bagadmenru-backend.tls.certresolver=myresolver"
      - "traefik.http.middlewares.corsheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,DELETE"
      - "traefik.http.middlewares.corsheader.headers.accesscontrolallowheaders=authorization,content-type,token"
      - "traefik.http.middlewares.corsheader.headers.accesscontrolalloworiginlist=https://beta.bagadmenru.bzh"
      - "traefik.http.middlewares.corsheader.headers.accesscontrolallowcredentials=true"
      - "traefik.http.routers.bagadmenru-backend.middlewares=corsheader@docker"
    depends_on:
      backend-migrate:
        condition: service_completed_successfully

  frontend:
    image: ghcr.io/maelgui/bagadmenru-v5/frontend
    expose:
      - 80
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bagadmenru-frontend.rule=Host(`beta.bagadmenru.bzh`)"
      - "traefik.http.routers.bagadmenru-frontend.tls.certresolver=myresolver"
    restart: unless-stopped
    environment:
      - VITE_BBE2_API_URL=https://api.beta.bagadmenru.bzh
      - VITE_OIDC_PROVIDER_URL=https://auth.beta.bagadmenru.bzh
      - VITE_OIDC_CLIENT_ID=bagad-frontend


  email-api:
    image: ghcr.io/maelgui/bagadmenru-v5/email-api
    environment:
      - RUST_LOG=tower_http=trace
      - APP_listen=0.0.0.0:9999
      - APP_email_from=contact@bagadmenru.bzh

      - APP_imap_domain=ssl0.ovh.net
      - APP_imap_port=993
      - APP_imap_username=contact@bagadmenru.bzh
      - APP_imap_password=${IMAP_PASSWORD}

      - APP_smtp_domain=ssl0.ovh.net
      - APP_smtp_port=465
      - APP_smtp_username=contact@bagadmenru.bzh
      - APP_smtp_password=${IMAP_PASSWORD}

  authorizer:
    image: openpolicyagent/opa
    command: ["run", "-s", "/policies", "-w", "-c", "/policies/config.yaml"]
    ports:
      - 8181:8181
    volumes:
      - ./opa:/policies

volumes:
  s3data:
  backend-pgdata:


networks:
  traefik:
    external: true
