apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DOMAIN: "prod.bagadmenru.bzh"
  FRONTEND_BASE_URL: "https://prod.bagadmenru.bzh"
  S3_BUCKET_NAME: "bagadmenruv5-data-prod"
  RELYING_PARTY_ID: "prod.bagadmenru.bzh"
  CORS_ALLOWED_ORIGINS: '["https://prod.bagadmenru.bzh"]'
  EMAIL_DRY_RUN: "false"
