[tool.poetry]
name = "bbe2"
version = "0.1.0"
description = ""
authors = ["Mael Guillossou <mael.guillossou@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.110.2"
uvicorn = "^0.21.1"
requests = "^2.31.0"
python-multipart = "^0.0.6"
boto3 = "^1.28.72"
pytest-cov = "^4.1.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
sqlalchemy = "^2.0.22"
psycopg = {extras = ["binary"], version = "^3.1.9"}
ics = "^0.7.2"
pydantic = "^2.4.2"
pydantic-settings = "^2.0.3"

[tool.poetry.group.dev.dependencies]
httpx = "^0.24.1"
pylint = "^3.0.2"
pytest = "^7.4.3"
autopep8 = "^1.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"
