/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Album
 */
export interface Album {
    /**
     * 
     * @type {string}
     * @memberof Album
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof Album
     */
    date: Date;
    /**
     * 
     * @type {number}
     * @memberof Album
     */
    id: number;
}

/**
 * Check if a given object implements the Album interface.
 */
export function instanceOfAlbum(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function AlbumFromJSON(json: any): Album {
    return AlbumFromJSONTyped(json, false);
}

export function AlbumFromJSONTyped(json: any, ignoreDiscriminator: boolean): Album {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'date': (new Date(json['date'])),
        'id': json['id'],
    };
}

export function AlbumToJSON(value?: Album | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'date': (value.date.toISOString().substr(0,10)),
        'id': value.id,
    };
}

