import love from 'eslint-config-love';
import pluginJsxA11y from 'eslint-plugin-jsx-a11y';
import pluginReact from 'eslint-plugin-react';
import pluginReactHooks from 'eslint-plugin-react-hooks';
import pluginStorybook from 'eslint-plugin-storybook';

export default [
  {
    ignores: ['public/**', 'dist/**'],
  },
  love,
  {
    files: ['**/*.{ts,tsx}'],
    ...pluginReact.configs.flat.recommended,
  },
  {
    files: ['**/*.{ts,tsx}'],
    ...pluginReact.configs.flat['jsx-runtime'],
  },
  {
    files: ['**/*.{ts,tsx}'],
    plugins: {
      'react-hooks': pluginReactHooks,
      'jsx-a11y': pluginJsxA11y,
    },
    rules: {
      ...pluginReactHooks.configs.recommended.rules,
      'jsx-a11y/label-has-associated-control': ['error', { assert: 'either' }],
    },
  },
  ...pluginStorybook.configs['flat/recommended'],
  {
    files: ['**/*.{ts,tsx}'],
    settings: {
      react: {
        version: 'detect',
      },
    },
    rules: {
      // Relax some rules from eslint-config-love for this project
      '@typescript-eslint/strict-boolean-expressions': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@typescript-eslint/no-confusing-void-expression': 'off',
      '@typescript-eslint/no-misused-promises': ['error', { checksVoidReturn: false }],
      'complexity': [
        'warn',
        { "maximum": 10 }
      ],
      '@typescript-eslint/no-magic-numbers': ["error", { "ignore": [0, 1, -1] }],
      "@typescript-eslint/prefer-destructuring": ["error", {
        "array": false,
        "object": true
      }],
    },
  },
  {
    // Test files: literal dates and counts are expected in assertions.
    files: ['src/**/*.test.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-magic-numbers': 'off',
    },
  },
  {
    // Vendored shadcn/ui components (generated by the shadcn CLI).
    // Keep them as close to upstream as possible: relax project-specific
    // strictness rules that upstream code does not follow.
    files: ['src/components/ui/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-magic-numbers': 'off',
      '@typescript-eslint/no-unsafe-type-assertion': 'off',
      '@typescript-eslint/consistent-type-assertions': 'off',
      '@typescript-eslint/consistent-type-definitions': 'off',
      '@typescript-eslint/consistent-type-imports': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      '@typescript-eslint/no-misused-promises': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      'complexity': 'off',
      'eqeqeq': 'off',
      'jsx-a11y/label-has-associated-control': 'off',
      'react-hooks/use-memo': 'off',
    },
  }
];
