apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DOMAIN: "beta.bagadmenru.bzh"
  FRONTEND_BASE_URL: "https://beta.bagadmenru.bzh"
  S3_BUCKET_NAME: "bagadmenruv5-data-beta"
  RELYING_PARTY_ID: "beta.bagadmenru.bzh"
  CORS_ALLOWED_ORIGINS: '["https://beta.bagadmenru.bzh"]'
  EMAIL_DRY_RUN: "true"
