/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Authenticatorattachment
 */
export interface Authenticatorattachment {
}

/**
 * Check if a given object implements the Authenticatorattachment interface.
 */
export function instanceOfAuthenticatorattachment(value: object): value is Authenticatorattachment {
    return true;
}

export function AuthenticatorattachmentFromJSON(json: any): Authenticatorattachment {
    return AuthenticatorattachmentFromJSONTyped(json, false);
}

export function AuthenticatorattachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Authenticatorattachment {
    return json;
}

export function AuthenticatorattachmentToJSON(json: any): Authenticatorattachment {
    return AuthenticatorattachmentToJSONTyped(json, false);
}

export function AuthenticatorattachmentToJSONTyped(value?: Authenticatorattachment | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

