/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The authenticator's attestation, as serialised by the browser.
 * 
 * NOT extra-forbidden: browsers/@simplewebauthn add convenience fields
 * (authenticatorData, publicKey, publicKeyAlgorithm, ...) that
 * verify_registration_response does not need; unknown fields are ignored
 * rather than rejected so newer browsers keep working.
 * @export
 * @interface AuthenticatorAttestationResponse
 */
export interface AuthenticatorAttestationResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthenticatorAttestationResponse
     */
    clientDataJSON: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticatorAttestationResponse
     */
    attestationObject: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthenticatorAttestationResponse
     */
    transports?: Array<string> | null;
}

/**
 * Check if a given object implements the AuthenticatorAttestationResponse interface.
 */
export function instanceOfAuthenticatorAttestationResponse(value: object): value is AuthenticatorAttestationResponse {
    if (!('clientDataJSON' in value) || value['clientDataJSON'] === undefined) return false;
    if (!('attestationObject' in value) || value['attestationObject'] === undefined) return false;
    return true;
}

export function AuthenticatorAttestationResponseFromJSON(json: any): AuthenticatorAttestationResponse {
    return AuthenticatorAttestationResponseFromJSONTyped(json, false);
}

export function AuthenticatorAttestationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticatorAttestationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'clientDataJSON': json['clientDataJSON'],
        'attestationObject': json['attestationObject'],
        'transports': json['transports'] == null ? undefined : json['transports'],
    };
}

export function AuthenticatorAttestationResponseToJSON(json: any): AuthenticatorAttestationResponse {
    return AuthenticatorAttestationResponseToJSONTyped(json, false);
}

export function AuthenticatorAttestationResponseToJSONTyped(value?: AuthenticatorAttestationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientDataJSON': value['clientDataJSON'],
        'attestationObject': value['attestationObject'],
        'transports': value['transports'],
    };
}

