/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResetPassword } from './ResetPassword';
import {
    ResetPasswordFromJSON,
    ResetPasswordFromJSONTyped,
    ResetPasswordToJSON,
    ResetPasswordToJSONTyped,
} from './ResetPassword';

/**
 * 
 * @export
 * @interface BodyResetPasswordApiV1AuthResetPost
 */
export interface BodyResetPasswordApiV1AuthResetPost {
    /**
     * 
     * @type {ResetPassword}
     * @memberof BodyResetPasswordApiV1AuthResetPost
     */
    body: ResetPassword;
    /**
     * 
     * @type {object}
     * @memberof BodyResetPasswordApiV1AuthResetPost
     */
    tokenPayload: object;
}

/**
 * Check if a given object implements the BodyResetPasswordApiV1AuthResetPost interface.
 */
export function instanceOfBodyResetPasswordApiV1AuthResetPost(value: object): value is BodyResetPasswordApiV1AuthResetPost {
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('tokenPayload' in value) || value['tokenPayload'] === undefined) return false;
    return true;
}

export function BodyResetPasswordApiV1AuthResetPostFromJSON(json: any): BodyResetPasswordApiV1AuthResetPost {
    return BodyResetPasswordApiV1AuthResetPostFromJSONTyped(json, false);
}

export function BodyResetPasswordApiV1AuthResetPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyResetPasswordApiV1AuthResetPost {
    if (json == null) {
        return json;
    }
    return {
        
        'body': ResetPasswordFromJSON(json['body']),
        'tokenPayload': json['token_payload'],
    };
}

export function BodyResetPasswordApiV1AuthResetPostToJSON(json: any): BodyResetPasswordApiV1AuthResetPost {
    return BodyResetPasswordApiV1AuthResetPostToJSONTyped(json, false);
}

export function BodyResetPasswordApiV1AuthResetPostToJSONTyped(value?: BodyResetPasswordApiV1AuthResetPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': ResetPasswordToJSON(value['body']),
        'token_payload': value['tokenPayload'],
    };
}

