/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Minimal event representation within a campaign response.
 * @export
 * @interface CampaignEvent
 */
export interface CampaignEvent {
    /**
     * 
     * @type {number}
     * @memberof CampaignEvent
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CampaignEvent
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof CampaignEvent
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof CampaignEvent
     */
    category: string;
}

/**
 * Check if a given object implements the CampaignEvent interface.
 */
export function instanceOfCampaignEvent(value: object): value is CampaignEvent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    return true;
}

export function CampaignEventFromJSON(json: any): CampaignEvent {
    return CampaignEventFromJSONTyped(json, false);
}

export function CampaignEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'date': (new Date(json['date'])),
        'category': json['category'],
    };
}

export function CampaignEventToJSON(json: any): CampaignEvent {
    return CampaignEventToJSONTyped(json, false);
}

export function CampaignEventToJSONTyped(value?: CampaignEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'date': ((value['date']).toISOString().substring(0,10)),
        'category': value['category'],
    };
}

