/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * No status field: status is server-enforced to 'draft'.
 * 
 * Unknown fields (e.g. a client-sent 'status') are ignored by Pydantic.
 * @export
 * @interface CampaignCreate
 */
export interface CampaignCreate {
    /**
     * 
     * @type {string}
     * @memberof CampaignCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignCreate
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CampaignCreate
     */
    groupId: number;
}

/**
 * Check if a given object implements the CampaignCreate interface.
 */
export function instanceOfCampaignCreate(value: object): value is CampaignCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    return true;
}

export function CampaignCreateFromJSON(json: any): CampaignCreate {
    return CampaignCreateFromJSONTyped(json, false);
}

export function CampaignCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'groupId': json['group_id'],
    };
}

export function CampaignCreateToJSON(json: any): CampaignCreate {
    return CampaignCreateToJSONTyped(json, false);
}

export function CampaignCreateToJSONTyped(value?: CampaignCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'group_id': value['groupId'],
    };
}

