/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CampaignEvent } from './CampaignEvent';
import {
    CampaignEventFromJSON,
    CampaignEventFromJSONTyped,
    CampaignEventToJSON,
    CampaignEventToJSONTyped,
} from './CampaignEvent';
import type { MinimalGroup } from './MinimalGroup';
import {
    MinimalGroupFromJSON,
    MinimalGroupFromJSONTyped,
    MinimalGroupToJSON,
    MinimalGroupToJSONTyped,
} from './MinimalGroup';

/**
 * 
 * @export
 * @interface Campaign
 */
export interface Campaign {
    /**
     * 
     * @type {number}
     * @memberof Campaign
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Campaign
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Campaign
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Campaign
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof Campaign
     */
    groupId: number;
    /**
     * 
     * @type {MinimalGroup}
     * @memberof Campaign
     */
    group: MinimalGroup;
    /**
     * 
     * @type {Date}
     * @memberof Campaign
     */
    createdAt: Date;
    /**
     * 
     * @type {Array<CampaignEvent>}
     * @memberof Campaign
     */
    events?: Array<CampaignEvent>;
    /**
     * 
     * @type {Date}
     * @memberof Campaign
     */
    firstEventDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Campaign
     */
    lastEventDate?: Date | null;
}

/**
 * Check if a given object implements the Campaign interface.
 */
export function instanceOfCampaign(value: object): value is Campaign {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    if (!('group' in value) || value['group'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CampaignFromJSON(json: any): Campaign {
    return CampaignFromJSONTyped(json, false);
}

export function CampaignFromJSONTyped(json: any, ignoreDiscriminator: boolean): Campaign {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'],
        'groupId': json['group_id'],
        'group': MinimalGroupFromJSON(json['group']),
        'createdAt': (new Date(json['created_at'])),
        'events': json['events'] == null ? undefined : ((json['events'] as Array<any>).map(CampaignEventFromJSON)),
        'firstEventDate': json['first_event_date'] == null ? undefined : (new Date(json['first_event_date'])),
        'lastEventDate': json['last_event_date'] == null ? undefined : (new Date(json['last_event_date'])),
    };
}

export function CampaignToJSON(json: any): Campaign {
    return CampaignToJSONTyped(json, false);
}

export function CampaignToJSONTyped(value?: Campaign | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'status': value['status'],
        'group_id': value['groupId'],
        'group': MinimalGroupToJSON(value['group']),
        'created_at': ((value['createdAt']).toISOString()),
        'events': value['events'] == null ? undefined : ((value['events'] as Array<any>).map(CampaignEventToJSON)),
        'first_event_date': value['firstEventDate'] == null ? undefined : ((value['firstEventDate'] as any).toISOString().substring(0,10)),
        'last_event_date': value['lastEventDate'] == null ? undefined : ((value['lastEventDate'] as any).toISOString().substring(0,10)),
    };
}

