/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A determination of the number of devices a credential can be used from
 * 
 * Members:
 *     `SINGLE_DEVICE`: A credential that is bound to a single device
 *     `MULTI_DEVICE`: A credential that can be used from multiple devices (e.g. passkeys)
 * 
 * https://w3c.github.io/webauthn/#sctn-credential-backup (L3 Draft)
 * @export
 */
export const CredentialDeviceType = {
    SingleDevice: 'single_device',
    MultiDevice: 'multi_device'
} as const;
export type CredentialDeviceType = typeof CredentialDeviceType[keyof typeof CredentialDeviceType];


export function instanceOfCredentialDeviceType(value: any): boolean {
    for (const key in CredentialDeviceType) {
        if (Object.prototype.hasOwnProperty.call(CredentialDeviceType, key)) {
            if (CredentialDeviceType[key as keyof typeof CredentialDeviceType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CredentialDeviceTypeFromJSON(json: any): CredentialDeviceType {
    return CredentialDeviceTypeFromJSONTyped(json, false);
}

export function CredentialDeviceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialDeviceType {
    return json as CredentialDeviceType;
}

export function CredentialDeviceTypeToJSON(value?: CredentialDeviceType | null): any {
    return value as any;
}

export function CredentialDeviceTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CredentialDeviceType {
    return value as CredentialDeviceType;
}

