/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginDataPasskey } from './LoginDataPasskey';
import {
    LoginDataPasskeyFromJSON,
    LoginDataPasskeyFromJSONTyped,
    LoginDataPasskeyToJSON,
    LoginDataPasskeyToJSONTyped,
} from './LoginDataPasskey';
import type { LoginDataPassword } from './LoginDataPassword';
import {
    LoginDataPasswordFromJSON,
    LoginDataPasswordFromJSONTyped,
    LoginDataPasswordToJSON,
    LoginDataPasswordToJSONTyped,
} from './LoginDataPassword';

/**
 * 
 * @export
 * @interface Data
 */
export interface Data {
    /**
     * 
     * @type {string}
     * @memberof Data
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof Data
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof Data
     */
    passkey: string;
}

/**
 * Check if a given object implements the Data interface.
 */
export function instanceOfData(value: object): value is Data {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('passkey' in value) || value['passkey'] === undefined) return false;
    return true;
}

export function DataFromJSON(json: any): Data {
    return DataFromJSONTyped(json, false);
}

export function DataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Data {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'passkey': json['passkey'],
    };
}

export function DataToJSON(json: any): Data {
    return DataToJSONTyped(json, false);
}

export function DataToJSONTyped(value?: Data | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'passkey': value['passkey'],
    };
}

