/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Costume } from './Costume';
import {
    CostumeFromJSON,
    CostumeFromJSONTyped,
    CostumeToJSON,
} from './Costume';

/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    description: string;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    date: Date;
    /**
     * 
     * @type {Costume}
     * @memberof Event
     */
    costume: Costume;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    category: string;
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    id: number;
}

/**
 * Check if a given object implements the Event interface.
 */
export function instanceOfEvent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "costume" in value;
    isInstance = isInstance && "category" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'date': (new Date(json['date'])),
        'costume': CostumeFromJSON(json['costume']),
        'category': json['category'],
        'id': json['id'],
    };
}

export function EventToJSON(value?: Event | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'date': (value.date.toISOString().substring(0,10)),
        'costume': CostumeToJSON(value.costume),
        'category': value.category,
        'id': value.id,
    };
}

