/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Costume } from './Costume';
import {
    CostumeFromJSON,
    CostumeFromJSONTyped,
    CostumeToJSON,
} from './Costume';

/**
 * 
 * @export
 * @interface EventCreate
 */
export interface EventCreate {
    /**
     * 
     * @type {string}
     * @memberof EventCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof EventCreate
     */
    description: string;
    /**
     * 
     * @type {Date}
     * @memberof EventCreate
     */
    date: Date;
    /**
     * 
     * @type {Costume}
     * @memberof EventCreate
     */
    costume: Costume;
}

/**
 * Check if a given object implements the EventCreate interface.
 */
export function instanceOfEventCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "costume" in value;

    return isInstance;
}

export function EventCreateFromJSON(json: any): EventCreate {
    return EventCreateFromJSONTyped(json, false);
}

export function EventCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'date': (new Date(json['date'])),
        'costume': CostumeFromJSON(json['costume']),
    };
}

export function EventCreateToJSON(value?: EventCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'date': (value.date.toISOString().substring(0,10)),
        'costume': CostumeToJSON(value.costume),
    };
}

