/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebAuthnCredentialDescriptor } from './WebAuthnCredentialDescriptor';
import {
    WebAuthnCredentialDescriptorFromJSON,
    WebAuthnCredentialDescriptorFromJSONTyped,
    WebAuthnCredentialDescriptorToJSON,
    WebAuthnCredentialDescriptorToJSONTyped,
} from './WebAuthnCredentialDescriptor';

/**
 * 
 * @export
 * @interface Excludecredentials
 */
export interface Excludecredentials {
}

/**
 * Check if a given object implements the Excludecredentials interface.
 */
export function instanceOfExcludecredentials(value: object): value is Excludecredentials {
    return true;
}

export function ExcludecredentialsFromJSON(json: any): Excludecredentials {
    return ExcludecredentialsFromJSONTyped(json, false);
}

export function ExcludecredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Excludecredentials {
    return json;
}

export function ExcludecredentialsToJSON(json: any): Excludecredentials {
    return ExcludecredentialsToJSONTyped(json, false);
}

export function ExcludecredentialsToJSONTyped(value?: Excludecredentials | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

