/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileOrFolderUpdate
 */
export interface FileOrFolderUpdate {
    /**
     * 
     * @type {string}
     * @memberof FileOrFolderUpdate
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof FileOrFolderUpdate
     */
    parentId?: number;
}

/**
 * Check if a given object implements the FileOrFolderUpdate interface.
 */
export function instanceOfFileOrFolderUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FileOrFolderUpdateFromJSON(json: any): FileOrFolderUpdate {
    return FileOrFolderUpdateFromJSONTyped(json, false);
}

export function FileOrFolderUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileOrFolderUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'parentId': !exists(json, 'parent_id') ? undefined : json['parent_id'],
    };
}

export function FileOrFolderUpdateToJSON(value?: FileOrFolderUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'parent_id': value.parentId,
    };
}

