/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileOrFolderType } from './FileOrFolderType';
import {
    FileOrFolderTypeFromJSON,
    FileOrFolderTypeFromJSONTyped,
    FileOrFolderTypeToJSON,
    FileOrFolderTypeToJSONTyped,
} from './FileOrFolderType';

/**
 * 
 * @export
 * @interface FileOrFolder
 */
export interface FileOrFolder {
    /**
     * 
     * @type {string}
     * @memberof FileOrFolder
     */
    name: string;
    /**
     * 
     * @type {FileOrFolderType}
     * @memberof FileOrFolder
     */
    type: FileOrFolderType;
    /**
     * 
     * @type {number}
     * @memberof FileOrFolder
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof FileOrFolder
     */
    parentId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FileOrFolder
     */
    fileKey?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FileOrFolder
     */
    childCount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FileOrFolder
     */
    fileUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileOrFolder
     */
    downloadUrl: string | null;
}



/**
 * Check if a given object implements the FileOrFolder interface.
 */
export function instanceOfFileOrFolder(value: object): value is FileOrFolder {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('fileUrl' in value) || value['fileUrl'] === undefined) return false;
    if (!('downloadUrl' in value) || value['downloadUrl'] === undefined) return false;
    return true;
}

export function FileOrFolderFromJSON(json: any): FileOrFolder {
    return FileOrFolderFromJSONTyped(json, false);
}

export function FileOrFolderFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileOrFolder {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': FileOrFolderTypeFromJSON(json['type']),
        'id': json['id'],
        'parentId': json['parent_id'] == null ? undefined : json['parent_id'],
        'fileKey': json['file_key'] == null ? undefined : json['file_key'],
        'childCount': json['child_count'] == null ? undefined : json['child_count'],
        'fileUrl': json['fileUrl'],
        'downloadUrl': json['downloadUrl'],
    };
}

export function FileOrFolderToJSON(json: any): FileOrFolder {
    return FileOrFolderToJSONTyped(json, false);
}

export function FileOrFolderToJSONTyped(value?: FileOrFolder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': FileOrFolderTypeToJSON(value['type']),
        'id': value['id'],
        'parent_id': value['parentId'],
        'file_key': value['fileKey'],
        'child_count': value['childCount'],
        'fileUrl': value['fileUrl'],
        'downloadUrl': value['downloadUrl'],
    };
}

