/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileAuthor
 */
export interface FileAuthor {
    /**
     * 
     * @type {string}
     * @memberof FileAuthor
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FileAuthor
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof FileAuthor
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof FileAuthor
     */
    readonly name: string;
}

/**
 * Check if a given object implements the FileAuthor interface.
 */
export function instanceOfFileAuthor(value: object): value is FileAuthor {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function FileAuthorFromJSON(json: any): FileAuthor {
    return FileAuthorFromJSONTyped(json, false);
}

export function FileAuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileAuthor {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'name': json['name'],
    };
}

export function FileAuthorToJSON(json: any): FileAuthor {
    return FileAuthorToJSONTyped(json, false);
}

export function FileAuthorToJSONTyped(value?: Omit<FileAuthor, 'name'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
    };
}

