/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FileOrFolderType } from './FileOrFolderType';
import {
    FileOrFolderTypeFromJSON,
    FileOrFolderTypeFromJSONTyped,
    FileOrFolderTypeToJSON,
} from './FileOrFolderType';

/**
 * 
 * @export
 * @interface FileOrFolder
 */
export interface FileOrFolder {
    /**
     * 
     * @type {string}
     * @memberof FileOrFolder
     */
    name: string;
    /**
     * 
     * @type {FileOrFolderType}
     * @memberof FileOrFolder
     */
    type: FileOrFolderType;
    /**
     * 
     * @type {number}
     * @memberof FileOrFolder
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof FileOrFolder
     */
    parentId?: number;
    /**
     * 
     * @type {string}
     * @memberof FileOrFolder
     */
    url?: string;
}

/**
 * Check if a given object implements the FileOrFolder interface.
 */
export function instanceOfFileOrFolder(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function FileOrFolderFromJSON(json: any): FileOrFolder {
    return FileOrFolderFromJSONTyped(json, false);
}

export function FileOrFolderFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileOrFolder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': FileOrFolderTypeFromJSON(json['type']),
        'id': json['id'],
        'parentId': !exists(json, 'parent_id') ? undefined : json['parent_id'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function FileOrFolderToJSON(value?: FileOrFolder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type': FileOrFolderTypeToJSON(value.type),
        'id': value.id,
        'parent_id': value.parentId,
        'url': value.url,
    };
}

