/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUploadUrlResponse
 */
export interface GetUploadUrlResponse {
    /**
     * 
     * @type {string}
     * @memberof GetUploadUrlResponse
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof GetUploadUrlResponse
     */
    key: string;
}

/**
 * Check if a given object implements the GetUploadUrlResponse interface.
 */
export function instanceOfGetUploadUrlResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function GetUploadUrlResponseFromJSON(json: any): GetUploadUrlResponse {
    return GetUploadUrlResponseFromJSONTyped(json, false);
}

export function GetUploadUrlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUploadUrlResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
        'key': json['key'],
    };
}

export function GetUploadUrlResponseToJSON(value?: GetUploadUrlResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'key': value.key,
    };
}

