/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GlobalStats
 */
export interface GlobalStats {
    /**
     * 
     */
    nResponses: number;
    /**
     * 
     */
    nEvents: number;
    /**
     * 
     */
    avgResponseTime: string | null;
    /**
     * 
     */
    nUpcomingEvent: number;
}

/**
 * Check if a given object implements the GlobalStats interface.
 */
export function instanceOfGlobalStats(value: object): value is GlobalStats {
    if ((!('nResponses' in (value as Record<string, any>)) && !('n_responses' in (value as Record<string, any>))) || ((value as Record<string, any>)['nResponses'] === undefined && (value as Record<string, any>)['n_responses'] === undefined)) return false;
    if ((!('nEvents' in (value as Record<string, any>)) && !('n_events' in (value as Record<string, any>))) || ((value as Record<string, any>)['nEvents'] === undefined && (value as Record<string, any>)['n_events'] === undefined)) return false;
    if ((!('avgResponseTime' in (value as Record<string, any>)) && !('avg_response_time' in (value as Record<string, any>))) || ((value as Record<string, any>)['avgResponseTime'] === undefined && (value as Record<string, any>)['avg_response_time'] === undefined)) return false;
    if ((!('nUpcomingEvent' in (value as Record<string, any>)) && !('n_upcoming_event' in (value as Record<string, any>))) || ((value as Record<string, any>)['nUpcomingEvent'] === undefined && (value as Record<string, any>)['n_upcoming_event'] === undefined)) return false;
    return true;
}

export function GlobalStatsFromJSON(json: any): GlobalStats {
    return GlobalStatsFromJSONTyped(json, false);
}

export function GlobalStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalStats {
    if (json == null) {
        return json;
    }
    return {
        
        'nResponses': json['n_responses'],
        'nEvents': json['n_events'],
        'avgResponseTime': json['avg_response_time'],
        'nUpcomingEvent': json['n_upcoming_event'],
    };
}

export function GlobalStatsToJSON(json: any): GlobalStats {
    return GlobalStatsToJSONTyped(json, false);
}

export function GlobalStatsToJSONTyped(value?: GlobalStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'n_responses': value['nResponses'],
        'n_events': value['nEvents'],
        'avg_response_time': value['avgResponseTime'],
        'n_upcoming_event': value['nUpcomingEvent'],
    };
}

