/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GlobalStats
 */
export interface GlobalStats {
    /**
     * 
     * @type {number}
     * @memberof GlobalStats
     */
    nResponses: number;
    /**
     * 
     * @type {number}
     * @memberof GlobalStats
     */
    nEvents: number;
    /**
     * 
     * @type {string}
     * @memberof GlobalStats
     */
    avgResponseTime: string | null;
    /**
     * 
     * @type {number}
     * @memberof GlobalStats
     */
    nUpcomingEvent: number;
}

/**
 * Check if a given object implements the GlobalStats interface.
 */
export function instanceOfGlobalStats(value: object): value is GlobalStats {
    if (!('nResponses' in value) || value['nResponses'] === undefined) return false;
    if (!('nEvents' in value) || value['nEvents'] === undefined) return false;
    if (!('avgResponseTime' in value) || value['avgResponseTime'] === undefined) return false;
    if (!('nUpcomingEvent' in value) || value['nUpcomingEvent'] === undefined) return false;
    return true;
}

export function GlobalStatsFromJSON(json: any): GlobalStats {
    return GlobalStatsFromJSONTyped(json, false);
}

export function GlobalStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalStats {
    if (json == null) {
        return json;
    }
    return {
        
        'nResponses': json['n_responses'],
        'nEvents': json['n_events'],
        'avgResponseTime': json['avg_response_time'],
        'nUpcomingEvent': json['n_upcoming_event'],
    };
}

export function GlobalStatsToJSON(value?: GlobalStats | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'n_responses': value['nResponses'],
        'n_events': value['nEvents'],
        'avg_response_time': value['avgResponseTime'],
        'n_upcoming_event': value['nUpcomingEvent'],
    };
}

