/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupUpdate
 */
export interface GroupUpdate {
    /**
     * 
     * @type {string}
     * @memberof GroupUpdate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GroupUpdate
     */
    color?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupUpdate
     */
    permissionIds: Array<string>;
}

/**
 * Check if a given object implements the GroupUpdate interface.
 */
export function instanceOfGroupUpdate(value: object): value is GroupUpdate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('permissionIds' in value) || value['permissionIds'] === undefined) return false;
    return true;
}

export function GroupUpdateFromJSON(json: any): GroupUpdate {
    return GroupUpdateFromJSONTyped(json, false);
}

export function GroupUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'color': json['color'] == null ? undefined : json['color'],
        'permissionIds': json['permission_ids'],
    };
}

export function GroupUpdateToJSON(value?: GroupUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'color': value['color'],
        'permission_ids': value['permissionIds'],
    };
}

