/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupCreate
 */
export interface GroupCreate {
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    color?: string;
    /**
     * 
     */
    mailingList: string | null;
    /**
     * 
     */
    roleIds: Array<string>;
    /**
     * 
     */
    isInstrument?: boolean;
}

/**
 * Check if a given object implements the GroupCreate interface.
 */
export function instanceOfGroupCreate(value: object): value is GroupCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('mailingList' in (value as Record<string, any>)) && !('mailing_list' in (value as Record<string, any>))) || ((value as Record<string, any>)['mailingList'] === undefined && (value as Record<string, any>)['mailing_list'] === undefined)) return false;
    if ((!('roleIds' in (value as Record<string, any>)) && !('role_ids' in (value as Record<string, any>))) || ((value as Record<string, any>)['roleIds'] === undefined && (value as Record<string, any>)['role_ids'] === undefined)) return false;
    return true;
}

export function GroupCreateFromJSON(json: any): GroupCreate {
    return GroupCreateFromJSONTyped(json, false);
}

export function GroupCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'color': json['color'] == null ? undefined : json['color'],
        'mailingList': json['mailing_list'],
        'roleIds': json['role_ids'],
        'isInstrument': json['is_instrument'] == null ? undefined : json['is_instrument'],
    };
}

export function GroupCreateToJSON(json: any): GroupCreate {
    return GroupCreateToJSONTyped(json, false);
}

export function GroupCreateToJSONTyped(value?: GroupCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'color': value['color'],
        'mailing_list': value['mailingList'],
        'role_ids': value['roleIds'],
        'is_instrument': value['isInstrument'],
    };
}

