/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * An email from the inbox (headers only).
 * @export
 * @interface InboxEmail
 */
export interface InboxEmail {
    /**
     * 
     */
    subject: string;
    /**
     * 
     */
    datetime: Date;
    /**
     * 
     */
    from?: string | null;
}

/**
 * Check if a given object implements the InboxEmail interface.
 */
export function instanceOfInboxEmail(value: object): value is InboxEmail {
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('datetime' in value) || value['datetime'] === undefined) return false;
    return true;
}

export function InboxEmailFromJSON(json: any): InboxEmail {
    return InboxEmailFromJSONTyped(json, false);
}

export function InboxEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): InboxEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'subject': json['subject'],
        'datetime': (json['datetime'] == null ? json['datetime'] : parseDateTime(json['datetime'])),
        'from': json['from'] === undefined ? undefined : json['from'] === null ? null : json['from'],
    };
}

export function InboxEmailToJSON(json: any): InboxEmail {
    return InboxEmailToJSONTyped(json, false);
}

export function InboxEmailToJSONTyped(value?: InboxEmail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subject': value['subject'],
        'datetime': value['datetime'] == null ? value['datetime'] : serializeDateTime(value['datetime']),
        'from': value['from'],
    };
}

