/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Public prefill data returned when opening a signup link.
 * 
 * Contains no secrets. ``email_locked`` is true only when the invitation email
 * was proven (EMAIL channel with a target address): the signup form then shows
 * the address read-only and no OTP is needed as long as it is unchanged.
 * @export
 * @interface InvitationInfo
 */
export interface InvitationInfo {
    /**
     * 
     * @type {string}
     * @memberof InvitationInfo
     */
    email?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof InvitationInfo
     */
    emailLocked?: boolean;
}

/**
 * Check if a given object implements the InvitationInfo interface.
 */
export function instanceOfInvitationInfo(value: object): value is InvitationInfo {
    return true;
}

export function InvitationInfoFromJSON(json: any): InvitationInfo {
    return InvitationInfoFromJSONTyped(json, false);
}

export function InvitationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'emailLocked': json['email_locked'] == null ? undefined : json['email_locked'],
    };
}

export function InvitationInfoToJSON(json: any): InvitationInfo {
    return InvitationInfoToJSONTyped(json, false);
}

export function InvitationInfoToJSONTyped(value?: InvitationInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'email_locked': value['emailLocked'],
    };
}

