/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginDataPassword
 */
export interface LoginDataPassword {
    /**
     * 
     * @type {string}
     * @memberof LoginDataPassword
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LoginDataPassword
     */
    password: string;
}

/**
 * Check if a given object implements the LoginDataPassword interface.
 */
export function instanceOfLoginDataPassword(value: object): value is LoginDataPassword {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LoginDataPasswordFromJSON(json: any): LoginDataPassword {
    return LoginDataPasswordFromJSONTyped(json, false);
}

export function LoginDataPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginDataPassword {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function LoginDataPasswordToJSON(json: any): LoginDataPassword {
    return LoginDataPasswordToJSONTyped(json, false);
}

export function LoginDataPasswordToJSONTyped(value?: LoginDataPassword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

