/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Body of ``POST /auth/login_code`` (single recovery sign-in endpoint).
 * 
 * ``via`` only labels the funnel metric (code typed by hand vs the emailed
 * link, which is the same call with both fields prefilled in its URL). It is
 * client-declared and carries no security meaning.
 * @export
 * @interface LoginCode
 */
export interface LoginCode {
    /**
     * 
     * @type {string}
     * @memberof LoginCode
     */
    grantId: string;
    /**
     * 
     * @type {string}
     * @memberof LoginCode
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof LoginCode
     */
    via?: LoginCodeViaEnum;
}


/**
 * @export
 */
export const LoginCodeViaEnum = {
    Code: 'code',
    Link: 'link'
} as const;
export type LoginCodeViaEnum = typeof LoginCodeViaEnum[keyof typeof LoginCodeViaEnum];


/**
 * Check if a given object implements the LoginCode interface.
 */
export function instanceOfLoginCode(value: object): value is LoginCode {
    if (!('grantId' in value) || value['grantId'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function LoginCodeFromJSON(json: any): LoginCode {
    return LoginCodeFromJSONTyped(json, false);
}

export function LoginCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginCode {
    if (json == null) {
        return json;
    }
    return {
        
        'grantId': json['grant_id'],
        'code': json['code'],
        'via': json['via'] == null ? undefined : json['via'],
    };
}

export function LoginCodeToJSON(json: any): LoginCode {
    return LoginCodeToJSONTyped(json, false);
}

export function LoginCodeToJSONTyped(value?: LoginCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grant_id': value['grantId'],
        'code': value['code'],
        'via': value['via'],
    };
}

