/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Optional logout body naming which account to sign out.
 * 
 * Defaults to the active account when omitted.
 * @export
 * @interface LogoutRequest
 */
export interface LogoutRequest {
    /**
     * 
     * @type {string}
     * @memberof LogoutRequest
     */
    accountId?: string | null;
}

/**
 * Check if a given object implements the LogoutRequest interface.
 */
export function instanceOfLogoutRequest(value: object): value is LogoutRequest {
    return true;
}

export function LogoutRequestFromJSON(json: any): LogoutRequest {
    return LogoutRequestFromJSONTyped(json, false);
}

export function LogoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogoutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
    };
}

export function LogoutRequestToJSON(json: any): LogoutRequest {
    return LogoutRequestToJSONTyped(json, false);
}

export function LogoutRequestToJSONTyped(value?: LogoutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
    };
}

