/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MembershipStatus } from './MembershipStatus';
import {
    MembershipStatusFromJSON,
    MembershipStatusFromJSONTyped,
    MembershipStatusToJSON,
    MembershipStatusToJSONTyped,
} from './MembershipStatus';
import type { MembershipHistoryItem } from './MembershipHistoryItem';
import {
    MembershipHistoryItemFromJSON,
    MembershipHistoryItemFromJSONTyped,
    MembershipHistoryItemToJSON,
    MembershipHistoryItemToJSONTyped,
} from './MembershipHistoryItem';

/**
 * Membership status plus history for a member.
 * @export
 * @interface MembershipInfo
 */
export interface MembershipInfo {
    /**
     * 
     * @type {MembershipStatus}
     * @memberof MembershipInfo
     */
    status: MembershipStatus;
    /**
     * 
     * @type {string}
     * @memberof MembershipInfo
     */
    currentSeason: string;
    /**
     * 
     * @type {string}
     * @memberof MembershipInfo
     */
    activeSeason?: string | null;
    /**
     * 
     * @type {Array<MembershipHistoryItem>}
     * @memberof MembershipInfo
     */
    history: Array<MembershipHistoryItem>;
}



/**
 * Check if a given object implements the MembershipInfo interface.
 */
export function instanceOfMembershipInfo(value: object): value is MembershipInfo {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('currentSeason' in value) || value['currentSeason'] === undefined) return false;
    if (!('history' in value) || value['history'] === undefined) return false;
    return true;
}

export function MembershipInfoFromJSON(json: any): MembershipInfo {
    return MembershipInfoFromJSONTyped(json, false);
}

export function MembershipInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MembershipInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'status': MembershipStatusFromJSON(json['status']),
        'currentSeason': json['current_season'],
        'activeSeason': json['active_season'] == null ? undefined : json['active_season'],
        'history': ((json['history'] as Array<any>).map(MembershipHistoryItemFromJSON)),
    };
}

export function MembershipInfoToJSON(json: any): MembershipInfo {
    return MembershipInfoToJSONTyped(json, false);
}

export function MembershipInfoToJSONTyped(value?: MembershipInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': MembershipStatusToJSON(value['status']),
        'current_season': value['currentSeason'],
        'active_season': value['activeSeason'],
        'history': ((value['history'] as Array<any>).map(MembershipHistoryItemToJSON)),
    };
}

