/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MinimalGroup
 */
export interface MinimalGroup {
    /**
     * 
     * @type {string}
     * @memberof MinimalGroup
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MinimalGroup
     */
    color?: string;
    /**
     * 
     * @type {number}
     * @memberof MinimalGroup
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof MinimalGroup
     */
    isInstrument?: boolean;
}

/**
 * Check if a given object implements the MinimalGroup interface.
 */
export function instanceOfMinimalGroup(value: object): value is MinimalGroup {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function MinimalGroupFromJSON(json: any): MinimalGroup {
    return MinimalGroupFromJSONTyped(json, false);
}

export function MinimalGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): MinimalGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'color': json['color'] == null ? undefined : json['color'],
        'id': json['id'],
        'isInstrument': json['is_instrument'] == null ? undefined : json['is_instrument'],
    };
}

export function MinimalGroupToJSON(json: any): MinimalGroup {
    return MinimalGroupToJSONTyped(json, false);
}

export function MinimalGroupToJSONTyped(value?: MinimalGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'color': value['color'],
        'id': value['id'],
        'is_instrument': value['isInstrument'],
    };
}

