/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FileType } from './FileType';
import {
    FileTypeFromJSON,
    FileTypeFromJSONTyped,
    FileTypeToJSON,
} from './FileType';

/**
 * 
 * @export
 * @interface ModelFile
 */
export interface ModelFile {
    /**
     * 
     * @type {FileType}
     * @memberof ModelFile
     */
    type: FileType;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelFile
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof ModelFile
     */
    isRoot: boolean;
}

/**
 * Check if a given object implements the ModelFile interface.
 */
export function instanceOfModelFile(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "isRoot" in value;

    return isInstance;
}

export function ModelFileFromJSON(json: any): ModelFile {
    return ModelFileFromJSONTyped(json, false);
}

export function ModelFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelFile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': FileTypeFromJSON(json['type']),
        'name': json['name'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'id': json['id'],
        'isRoot': json['is_root'],
    };
}

export function ModelFileToJSON(value?: ModelFile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': FileTypeToJSON(value.type),
        'name': value.name,
        'url': value.url,
        'id': value.id,
        'is_root': value.isRoot,
    };
}

