/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MyProfileUpdate
 */
export interface MyProfileUpdate {
    /**
     * 
     */
    firstName: string;
    /**
     * 
     */
    lastName: string;
    /**
     * 
     */
    pictureKey?: string | null;
    /**
     * 
     */
    receivesEmails: boolean;
    /**
     * 
     */
    receivesPush: boolean;
}

/**
 * Check if a given object implements the MyProfileUpdate interface.
 */
export function instanceOfMyProfileUpdate(value: object): value is MyProfileUpdate {
    if ((!('firstName' in (value as Record<string, any>)) && !('first_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['firstName'] === undefined && (value as Record<string, any>)['first_name'] === undefined)) return false;
    if ((!('lastName' in (value as Record<string, any>)) && !('last_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['lastName'] === undefined && (value as Record<string, any>)['last_name'] === undefined)) return false;
    if ((!('receivesEmails' in (value as Record<string, any>)) && !('receives_emails' in (value as Record<string, any>))) || ((value as Record<string, any>)['receivesEmails'] === undefined && (value as Record<string, any>)['receives_emails'] === undefined)) return false;
    if ((!('receivesPush' in (value as Record<string, any>)) && !('receives_push' in (value as Record<string, any>))) || ((value as Record<string, any>)['receivesPush'] === undefined && (value as Record<string, any>)['receives_push'] === undefined)) return false;
    return true;
}

export function MyProfileUpdateFromJSON(json: any): MyProfileUpdate {
    return MyProfileUpdateFromJSONTyped(json, false);
}

export function MyProfileUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyProfileUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'pictureKey': json['picture_key'] === undefined ? undefined : json['picture_key'] === null ? null : json['picture_key'],
        'receivesEmails': json['receives_emails'],
        'receivesPush': json['receives_push'],
    };
}

export function MyProfileUpdateToJSON(json: any): MyProfileUpdate {
    return MyProfileUpdateToJSONTyped(json, false);
}

export function MyProfileUpdateToJSONTyped(value?: MyProfileUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'picture_key': value['pictureKey'],
        'receives_emails': value['receivesEmails'],
        'receives_push': value['receivesPush'],
    };
}

