/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MinimalGroup } from './MinimalGroup';
import {
    MinimalGroupFromJSON,
    MinimalGroupFromJSONTyped,
    MinimalGroupToJSON,
    MinimalGroupToJSONTyped,
} from './MinimalGroup';

/**
 * 
 * @export
 * @interface MyProfile
 */
export interface MyProfile {
    /**
     * 
     * @type {string}
     * @memberof MyProfile
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof MyProfile
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof MyProfile
     */
    pictureKey?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MyProfile
     */
    id: string;
    /**
     * 
     * @type {Array<MinimalGroup>}
     * @memberof MyProfile
     */
    groups: Array<MinimalGroup>;
    /**
     * 
     * @type {MinimalGroup}
     * @memberof MyProfile
     */
    instrument?: MinimalGroup | null;
    /**
     * 
     * @type {string}
     * @memberof MyProfile
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof MyProfile
     */
    pictureUrl: string | null;
}

/**
 * Check if a given object implements the MyProfile interface.
 */
export function instanceOfMyProfile(value: object): value is MyProfile {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('groups' in value) || value['groups'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('pictureUrl' in value) || value['pictureUrl'] === undefined) return false;
    return true;
}

export function MyProfileFromJSON(json: any): MyProfile {
    return MyProfileFromJSONTyped(json, false);
}

export function MyProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'pictureKey': json['picture_key'] == null ? undefined : json['picture_key'],
        'id': json['id'],
        'groups': ((json['groups'] as Array<any>).map(MinimalGroupFromJSON)),
        'instrument': json['instrument'] == null ? undefined : MinimalGroupFromJSON(json['instrument']),
        'email': json['email'],
        'pictureUrl': json['picture_url'],
    };
}

export function MyProfileToJSON(json: any): MyProfile {
    return MyProfileToJSONTyped(json, false);
}

export function MyProfileToJSONTyped(value?: MyProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'picture_key': value['pictureKey'],
        'id': value['id'],
        'groups': ((value['groups'] as Array<any>).map(MinimalGroupToJSON)),
        'instrument': MinimalGroupToJSON(value['instrument']),
        'email': value['email'],
        'picture_url': value['pictureUrl'],
    };
}

