/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MyStats
 */
export interface MyStats {
    /**
     * 
     * @type {number}
     * @memberof MyStats
     */
    nResponses: number;
    /**
     * 
     * @type {number}
     * @memberof MyStats
     */
    nPositiveResponses: number;
    /**
     * 
     * @type {string}
     * @memberof MyStats
     */
    avgResponseTime: string;
    /**
     * 
     * @type {number}
     * @memberof MyStats
     */
    responsesNeeded: number;
}

/**
 * Check if a given object implements the MyStats interface.
 */
export function instanceOfMyStats(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nResponses" in value;
    isInstance = isInstance && "nPositiveResponses" in value;
    isInstance = isInstance && "avgResponseTime" in value;
    isInstance = isInstance && "responsesNeeded" in value;

    return isInstance;
}

export function MyStatsFromJSON(json: any): MyStats {
    return MyStatsFromJSONTyped(json, false);
}

export function MyStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nResponses': json['n_responses'],
        'nPositiveResponses': json['n_positive_responses'],
        'avgResponseTime': json['avg_response_time'],
        'responsesNeeded': json['responses_needed'],
    };
}

export function MyStatsToJSON(value?: MyStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'n_responses': value.nResponses,
        'n_positive_responses': value.nPositiveResponses,
        'avg_response_time': value.avgResponseTime,
        'responses_needed': value.responsesNeeded,
    };
}

