/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request an email verification code for the address the invitee entered.
 * @export
 * @interface OtpRequest
 */
export interface OtpRequest {
    /**
     * 
     * @type {string}
     * @memberof OtpRequest
     */
    email: string;
}

/**
 * Check if a given object implements the OtpRequest interface.
 */
export function instanceOfOtpRequest(value: object): value is OtpRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function OtpRequestFromJSON(json: any): OtpRequest {
    return OtpRequestFromJSONTyped(json, false);
}

export function OtpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OtpRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function OtpRequestToJSON(json: any): OtpRequest {
    return OtpRequestToJSONTyped(json, false);
}

export function OtpRequestToJSONTyped(value?: OtpRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

