/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Payload for ``PublicKeyCredential.signalAllAcceptedCredentials()``.
 * 
 * Returned by the passkey DELETE endpoint so the client can tell the passkey
 * provider (Keychain, Google Password Manager…) which credentials are still
 * valid — the provider then deletes its copy of the removed one instead of
 * keeping an orphan that would fail at the next login. All identifiers use
 * base64url **without padding**, the encoding the WebAuthn Signal API
 * expects (unlike ``Passkey.credential_id``, which keeps its historical
 * padded form).
 * @export
 * @interface PasskeySignal
 */
export interface PasskeySignal {
    /**
     * 
     */
    rpId: string;
    /**
     * 
     */
    userHandle: string;
    /**
     * 
     */
    remainingCredentialIds: Array<string>;
}

/**
 * Check if a given object implements the PasskeySignal interface.
 */
export function instanceOfPasskeySignal(value: object): value is PasskeySignal {
    if ((!('rpId' in (value as Record<string, any>)) && !('rp_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['rpId'] === undefined && (value as Record<string, any>)['rp_id'] === undefined)) return false;
    if ((!('userHandle' in (value as Record<string, any>)) && !('user_handle' in (value as Record<string, any>))) || ((value as Record<string, any>)['userHandle'] === undefined && (value as Record<string, any>)['user_handle'] === undefined)) return false;
    if ((!('remainingCredentialIds' in (value as Record<string, any>)) && !('remaining_credential_ids' in (value as Record<string, any>))) || ((value as Record<string, any>)['remainingCredentialIds'] === undefined && (value as Record<string, any>)['remaining_credential_ids'] === undefined)) return false;
    return true;
}

export function PasskeySignalFromJSON(json: any): PasskeySignal {
    return PasskeySignalFromJSONTyped(json, false);
}

export function PasskeySignalFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasskeySignal {
    if (json == null) {
        return json;
    }
    return {
        
        'rpId': json['rp_id'],
        'userHandle': json['user_handle'],
        'remainingCredentialIds': json['remaining_credential_ids'],
    };
}

export function PasskeySignalToJSON(json: any): PasskeySignal {
    return PasskeySignalToJSONTyped(json, false);
}

export function PasskeySignalToJSONTyped(value?: PasskeySignal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rp_id': value['rpId'],
        'user_handle': value['userHandle'],
        'remaining_credential_ids': value['remainingCredentialIds'],
    };
}

