/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { CredentialDeviceType } from './CredentialDeviceType';
import {
    CredentialDeviceTypeFromJSON,
    CredentialDeviceTypeFromJSONTyped,
    CredentialDeviceTypeToJSON,
    CredentialDeviceTypeToJSONTyped,
} from './CredentialDeviceType';

/**
 * 
 * @export
 * @interface Passkey
 */
export interface Passkey {
    /**
     * 
     */
    credentialId: string;
    /**
     * 
     */
    signCount: number;
    /**
     * 
     */
    transports: string;
    /**
     * 
     */
    deviceType: CredentialDeviceType;
    /**
     * 
     */
    backUp: boolean;
    /**
     * 
     */
    aaguid: string;
    /**
     * 
     */
    lastUseAt?: Date | null;
    /**
     * 
     */
    lastUseIp?: string | null;
    /**
     * 
     */
    lastUseUa?: string | null;
    /**
     * 
     */
    createdAt: Date;
}



/**
 * Check if a given object implements the Passkey interface.
 */
export function instanceOfPasskey(value: object): value is Passkey {
    if ((!('credentialId' in (value as Record<string, any>)) && !('credential_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['credentialId'] === undefined && (value as Record<string, any>)['credential_id'] === undefined)) return false;
    if ((!('signCount' in (value as Record<string, any>)) && !('sign_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['signCount'] === undefined && (value as Record<string, any>)['sign_count'] === undefined)) return false;
    if (!('transports' in value) || value['transports'] === undefined) return false;
    if ((!('deviceType' in (value as Record<string, any>)) && !('device_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['deviceType'] === undefined && (value as Record<string, any>)['device_type'] === undefined)) return false;
    if ((!('backUp' in (value as Record<string, any>)) && !('back_up' in (value as Record<string, any>))) || ((value as Record<string, any>)['backUp'] === undefined && (value as Record<string, any>)['back_up'] === undefined)) return false;
    if (!('aaguid' in value) || value['aaguid'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function PasskeyFromJSON(json: any): Passkey {
    return PasskeyFromJSONTyped(json, false);
}

export function PasskeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Passkey {
    if (json == null) {
        return json;
    }
    return {
        
        'credentialId': json['credential_id'],
        'signCount': json['sign_count'],
        'transports': json['transports'],
        'deviceType': CredentialDeviceTypeFromJSON(json['device_type']),
        'backUp': json['back_up'],
        'aaguid': json['aaguid'],
        'lastUseAt': json['last_use_at'] === undefined ? undefined : json['last_use_at'] === null ? null : (parseDateTime(json['last_use_at'])),
        'lastUseIp': json['last_use_ip'] === undefined ? undefined : json['last_use_ip'] === null ? null : json['last_use_ip'],
        'lastUseUa': json['last_use_ua'] === undefined ? undefined : json['last_use_ua'] === null ? null : json['last_use_ua'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
    };
}

export function PasskeyToJSON(json: any): Passkey {
    return PasskeyToJSONTyped(json, false);
}

export function PasskeyToJSONTyped(value?: Passkey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credential_id': value['credentialId'],
        'sign_count': value['signCount'],
        'transports': value['transports'],
        'device_type': CredentialDeviceTypeToJSON(value['deviceType']),
        'back_up': value['backUp'],
        'aaguid': value['aaguid'],
        'last_use_at': value['lastUseAt'] == null ? value['lastUseAt'] : serializeDateTime(value['lastUseAt']),
        'last_use_ip': value['lastUseIp'],
        'last_use_ua': value['lastUseUa'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

