/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    pictureKey: string | null;
    /**
     * 
     * @type {number}
     * @memberof Profile
     */
    instrumentId: number | null;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    pictureUrl: string | null;
}

/**
 * Check if a given object implements the Profile interface.
 */
export function instanceOfProfile(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pictureKey" in value;
    isInstance = isInstance && "instrumentId" in value;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "lastName" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "pictureUrl" in value;

    return isInstance;
}

export function ProfileFromJSON(json: any): Profile {
    return ProfileFromJSONTyped(json, false);
}

export function ProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Profile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pictureKey': json['picture_key'],
        'instrumentId': json['instrument_id'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'email': json['email'],
        'id': json['id'],
        'pictureUrl': json['picture_url'],
    };
}

export function ProfileToJSON(value?: Profile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'picture_key': value.pictureKey,
        'instrument_id': value.instrumentId,
        'first_name': value.firstName,
        'last_name': value.lastName,
        'email': value.email,
        'id': value.id,
        'picture_url': value.pictureUrl,
    };
}

