/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MembershipStatus } from './MembershipStatus';
import {
    MembershipStatusFromJSON,
    MembershipStatusFromJSONTyped,
    MembershipStatusToJSON,
    MembershipStatusToJSONTyped,
} from './MembershipStatus';
import type { MinimalGroup } from './MinimalGroup';
import {
    MinimalGroupFromJSON,
    MinimalGroupFromJSONTyped,
    MinimalGroupToJSON,
    MinimalGroupToJSONTyped,
} from './MinimalGroup';

/**
 * 
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     * 
     */
    firstName: string;
    /**
     * 
     */
    lastName: string;
    /**
     * 
     */
    pictureKey?: string | null;
    /**
     * 
     */
    receivesEmails: boolean;
    /**
     * 
     */
    receivesPush: boolean;
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    groups: Array<MinimalGroup>;
    /**
     * 
     */
    instrument?: MinimalGroup | null;
    /**
     * 
     */
    isActive: boolean;
    /**
     * 
     */
    membershipStatus?: MembershipStatus | null;
    /**
     * 
     */
    membershipActiveSeason?: string | null;
    /**
     * 
     */
    hasPassword?: boolean | null;
    /**
     * 
     */
    readonly pictureUrl: string | null;
}



/**
 * Check if a given object implements the Profile interface.
 */
export function instanceOfProfile(value: object): value is Profile {
    if ((!('firstName' in (value as Record<string, any>)) && !('first_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['firstName'] === undefined && (value as Record<string, any>)['first_name'] === undefined)) return false;
    if ((!('lastName' in (value as Record<string, any>)) && !('last_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['lastName'] === undefined && (value as Record<string, any>)['last_name'] === undefined)) return false;
    if ((!('receivesEmails' in (value as Record<string, any>)) && !('receives_emails' in (value as Record<string, any>))) || ((value as Record<string, any>)['receivesEmails'] === undefined && (value as Record<string, any>)['receives_emails'] === undefined)) return false;
    if ((!('receivesPush' in (value as Record<string, any>)) && !('receives_push' in (value as Record<string, any>))) || ((value as Record<string, any>)['receivesPush'] === undefined && (value as Record<string, any>)['receives_push'] === undefined)) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('groups' in value) || value['groups'] === undefined) return false;
    if ((!('isActive' in (value as Record<string, any>)) && !('is_active' in (value as Record<string, any>))) || ((value as Record<string, any>)['isActive'] === undefined && (value as Record<string, any>)['is_active'] === undefined)) return false;
    if ((!('pictureUrl' in (value as Record<string, any>)) && !('picture_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['pictureUrl'] === undefined && (value as Record<string, any>)['picture_url'] === undefined)) return false;
    return true;
}

export function ProfileFromJSON(json: any): Profile {
    return ProfileFromJSONTyped(json, false);
}

export function ProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Profile {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'pictureKey': json['picture_key'] === undefined ? undefined : json['picture_key'] === null ? null : json['picture_key'],
        'receivesEmails': json['receives_emails'],
        'receivesPush': json['receives_push'],
        'email': json['email'],
        'id': json['id'],
        'groups': ((json['groups'] as Array<any>).map(MinimalGroupFromJSON)),
        'instrument': json['instrument'] === undefined ? undefined : json['instrument'] === null ? null : MinimalGroupFromJSON(json['instrument']),
        'isActive': json['is_active'],
        'membershipStatus': json['membership_status'] === undefined ? undefined : json['membership_status'] === null ? null : MembershipStatusFromJSON(json['membership_status']),
        'membershipActiveSeason': json['membership_active_season'] === undefined ? undefined : json['membership_active_season'] === null ? null : json['membership_active_season'],
        'hasPassword': json['has_password'] === undefined ? undefined : json['has_password'] === null ? null : json['has_password'],
        'pictureUrl': json['picture_url'],
    };
}

export function ProfileToJSON(json: any): Profile {
    return ProfileToJSONTyped(json, false);
}

export function ProfileToJSONTyped(value?: Omit<Profile, 'pictureUrl'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'picture_key': value['pictureKey'],
        'receives_emails': value['receivesEmails'],
        'receives_push': value['receivesPush'],
        'email': value['email'],
        'id': value['id'],
        'groups': ((value['groups'] as Array<any>).map(MinimalGroupToJSON)),
        'instrument': MinimalGroupToJSON(value['instrument']),
        'is_active': value['isActive'],
        'membership_status': MembershipStatusToJSON(value['membershipStatus']),
        'membership_active_season': value['membershipActiveSeason'],
        'has_password': value['hasPassword'],
    };
}

