/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileUpdate
 */
export interface ProfileUpdate {
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdate
     */
    picture?: string;
}

/**
 * Check if a given object implements the ProfileUpdate interface.
 */
export function instanceOfProfileUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfileUpdateFromJSON(json: any): ProfileUpdate {
    return ProfileUpdateFromJSONTyped(json, false);
}

export function ProfileUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'picture': !exists(json, 'picture') ? undefined : json['picture'],
    };
}

export function ProfileUpdateToJSON(value?: ProfileUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'picture': value.picture,
    };
}

