/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileCreate
 */
export interface ProfileCreate {
    /**
     * 
     * @type {string}
     * @memberof ProfileCreate
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileCreate
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileCreate
     */
    pictureKey?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProfileCreate
     */
    receivesEmails: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProfileCreate
     */
    receivesPush: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProfileCreate
     */
    instrumentId: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof ProfileCreate
     */
    groupIds: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof ProfileCreate
     */
    email: string;
}

/**
 * Check if a given object implements the ProfileCreate interface.
 */
export function instanceOfProfileCreate(value: object): value is ProfileCreate {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('receivesEmails' in value) || value['receivesEmails'] === undefined) return false;
    if (!('receivesPush' in value) || value['receivesPush'] === undefined) return false;
    if (!('instrumentId' in value) || value['instrumentId'] === undefined) return false;
    if (!('groupIds' in value) || value['groupIds'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ProfileCreateFromJSON(json: any): ProfileCreate {
    return ProfileCreateFromJSONTyped(json, false);
}

export function ProfileCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'pictureKey': json['picture_key'] == null ? undefined : json['picture_key'],
        'receivesEmails': json['receives_emails'],
        'receivesPush': json['receives_push'],
        'instrumentId': json['instrument_id'],
        'groupIds': json['group_ids'],
        'email': json['email'],
    };
}

export function ProfileCreateToJSON(json: any): ProfileCreate {
    return ProfileCreateToJSONTyped(json, false);
}

export function ProfileCreateToJSONTyped(value?: ProfileCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'picture_key': value['pictureKey'],
        'receives_emails': value['receivesEmails'],
        'receives_push': value['receivesPush'],
        'instrument_id': value['instrumentId'],
        'group_ids': value['groupIds'],
        'email': value['email'],
    };
}

