/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileUpdate
 */
export interface ProfileUpdate {
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdate
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdate
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdate
     */
    pictureKey: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProfileUpdate
     */
    instrumentId: number | null;
}

/**
 * Check if a given object implements the ProfileUpdate interface.
 */
export function instanceOfProfileUpdate(value: object): value is ProfileUpdate {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('pictureKey' in value) || value['pictureKey'] === undefined) return false;
    if (!('instrumentId' in value) || value['instrumentId'] === undefined) return false;
    return true;
}

export function ProfileUpdateFromJSON(json: any): ProfileUpdate {
    return ProfileUpdateFromJSONTyped(json, false);
}

export function ProfileUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'pictureKey': json['picture_key'],
        'instrumentId': json['instrument_id'],
    };
}

export function ProfileUpdateToJSON(value?: ProfileUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'picture_key': value['pictureKey'],
        'instrument_id': value['instrumentId'],
    };
}

