/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Authenticatorattachment } from './Authenticatorattachment';
import {
    AuthenticatorattachmentFromJSON,
    AuthenticatorattachmentFromJSONTyped,
    AuthenticatorattachmentToJSON,
    AuthenticatorattachmentToJSONTyped,
} from './Authenticatorattachment';
import type { Userverification } from './Userverification';
import {
    UserverificationFromJSON,
    UserverificationFromJSONTyped,
    UserverificationToJSON,
    UserverificationToJSONTyped,
} from './Userverification';
import type { WebAuthnAuthenticatorSelection } from './WebAuthnAuthenticatorSelection';
import {
    WebAuthnAuthenticatorSelectionFromJSON,
    WebAuthnAuthenticatorSelectionFromJSONTyped,
    WebAuthnAuthenticatorSelectionToJSON,
    WebAuthnAuthenticatorSelectionToJSONTyped,
} from './WebAuthnAuthenticatorSelection';
import type { Requireresidentkey } from './Requireresidentkey';
import {
    RequireresidentkeyFromJSON,
    RequireresidentkeyFromJSONTyped,
    RequireresidentkeyToJSON,
    RequireresidentkeyToJSONTyped,
} from './Requireresidentkey';
import type { Residentkey } from './Residentkey';
import {
    ResidentkeyFromJSON,
    ResidentkeyFromJSONTyped,
    ResidentkeyToJSON,
    ResidentkeyToJSONTyped,
} from './Residentkey';

/**
 * 
 * @export
 * @interface PublicKeyCredentialCreationOptionsAuthenticatorSelection
 */
export interface PublicKeyCredentialCreationOptionsAuthenticatorSelection {
    /**
     * 
     * @type {Authenticatorattachment}
     * @memberof PublicKeyCredentialCreationOptionsAuthenticatorSelection
     */
    authenticatorAttachment?: Authenticatorattachment;
    /**
     * 
     * @type {Residentkey}
     * @memberof PublicKeyCredentialCreationOptionsAuthenticatorSelection
     */
    residentKey?: Residentkey;
    /**
     * 
     * @type {Requireresidentkey}
     * @memberof PublicKeyCredentialCreationOptionsAuthenticatorSelection
     */
    requireResidentKey?: Requireresidentkey;
    /**
     * 
     * @type {Userverification}
     * @memberof PublicKeyCredentialCreationOptionsAuthenticatorSelection
     */
    userVerification?: Userverification;
}

/**
 * Check if a given object implements the PublicKeyCredentialCreationOptionsAuthenticatorSelection interface.
 */
export function instanceOfPublicKeyCredentialCreationOptionsAuthenticatorSelection(value: object): value is PublicKeyCredentialCreationOptionsAuthenticatorSelection {
    return true;
}

export function PublicKeyCredentialCreationOptionsAuthenticatorSelectionFromJSON(json: any): PublicKeyCredentialCreationOptionsAuthenticatorSelection {
    return PublicKeyCredentialCreationOptionsAuthenticatorSelectionFromJSONTyped(json, false);
}

export function PublicKeyCredentialCreationOptionsAuthenticatorSelectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicKeyCredentialCreationOptionsAuthenticatorSelection {
    if (json == null) {
        return json;
    }
    return {
        
        'authenticatorAttachment': json['authenticatorAttachment'] == null ? undefined : AuthenticatorattachmentFromJSON(json['authenticatorAttachment']),
        'residentKey': json['residentKey'] == null ? undefined : ResidentkeyFromJSON(json['residentKey']),
        'requireResidentKey': json['requireResidentKey'] == null ? undefined : RequireresidentkeyFromJSON(json['requireResidentKey']),
        'userVerification': json['userVerification'] == null ? undefined : UserverificationFromJSON(json['userVerification']),
    };
}

export function PublicKeyCredentialCreationOptionsAuthenticatorSelectionToJSON(json: any): PublicKeyCredentialCreationOptionsAuthenticatorSelection {
    return PublicKeyCredentialCreationOptionsAuthenticatorSelectionToJSONTyped(json, false);
}

export function PublicKeyCredentialCreationOptionsAuthenticatorSelectionToJSONTyped(value?: PublicKeyCredentialCreationOptionsAuthenticatorSelection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authenticatorAttachment': AuthenticatorattachmentToJSON(value['authenticatorAttachment']),
        'residentKey': ResidentkeyToJSON(value['residentKey']),
        'requireResidentKey': RequireresidentkeyToJSON(value['requireResidentKey']),
        'userVerification': UserverificationToJSON(value['userVerification']),
    };
}

