/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Timeout } from './Timeout';
import {
    TimeoutFromJSON,
    TimeoutFromJSONTyped,
    TimeoutToJSON,
    TimeoutToJSONTyped,
} from './Timeout';
import type { Userverification } from './Userverification';
import {
    UserverificationFromJSON,
    UserverificationFromJSONTyped,
    UserverificationToJSON,
    UserverificationToJSONTyped,
} from './Userverification';
import type { Allowcredentials } from './Allowcredentials';
import {
    AllowcredentialsFromJSON,
    AllowcredentialsFromJSONTyped,
    AllowcredentialsToJSON,
    AllowcredentialsToJSONTyped,
} from './Allowcredentials';
import type { Rpid } from './Rpid';
import {
    RpidFromJSON,
    RpidFromJSONTyped,
    RpidToJSON,
    RpidToJSONTyped,
} from './Rpid';

/**
 * Response of GET /auth/login (authentication ceremony input).
 * @export
 * @interface PublicKeyCredentialRequestOptions
 */
export interface PublicKeyCredentialRequestOptions {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof PublicKeyCredentialRequestOptions
     */
    challenge: string;
    /**
     * 
     * @type {Timeout}
     * @memberof PublicKeyCredentialRequestOptions
     */
    timeout?: Timeout;
    /**
     * 
     * @type {Rpid}
     * @memberof PublicKeyCredentialRequestOptions
     */
    rpId?: Rpid;
    /**
     * 
     * @type {Allowcredentials}
     * @memberof PublicKeyCredentialRequestOptions
     */
    allowCredentials?: Allowcredentials;
    /**
     * 
     * @type {Userverification}
     * @memberof PublicKeyCredentialRequestOptions
     */
    userVerification?: Userverification;
}

/**
 * Check if a given object implements the PublicKeyCredentialRequestOptions interface.
 */
export function instanceOfPublicKeyCredentialRequestOptions(value: object): value is PublicKeyCredentialRequestOptions {
    if (!('challenge' in value) || value['challenge'] === undefined) return false;
    return true;
}

export function PublicKeyCredentialRequestOptionsFromJSON(json: any): PublicKeyCredentialRequestOptions {
    return PublicKeyCredentialRequestOptionsFromJSONTyped(json, false);
}

export function PublicKeyCredentialRequestOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicKeyCredentialRequestOptions {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'challenge': json['challenge'],
        'timeout': json['timeout'] == null ? undefined : TimeoutFromJSON(json['timeout']),
        'rpId': json['rpId'] == null ? undefined : RpidFromJSON(json['rpId']),
        'allowCredentials': json['allowCredentials'] == null ? undefined : AllowcredentialsFromJSON(json['allowCredentials']),
        'userVerification': json['userVerification'] == null ? undefined : UserverificationFromJSON(json['userVerification']),
    };
}

export function PublicKeyCredentialRequestOptionsToJSON(json: any): PublicKeyCredentialRequestOptions {
    return PublicKeyCredentialRequestOptionsToJSONTyped(json, false);
}

export function PublicKeyCredentialRequestOptionsToJSONTyped(value?: PublicKeyCredentialRequestOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'challenge': value['challenge'],
        'timeout': TimeoutToJSON(value['timeout']),
        'rpId': RpidToJSON(value['rpId']),
        'allowCredentials': AllowcredentialsToJSON(value['allowCredentials']),
        'userVerification': UserverificationToJSON(value['userVerification']),
    };
}

