/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A push-subscribed device belonging to the current user.
 * 
 * Never exposes the encryption keys (p256dh/auth) nor the raw endpoint URL.
 * The raw user_agent is returned so the frontend can render a friendly label;
 * last_used_at is the time of the last successfully sent push (null if none
 * sent yet). device_hash is a stable, non-reversible fingerprint of the push
 * endpoint: the browser hashes its own endpoint the same way to recognise
 * which row is "this device" without the endpoint ever being exposed.
 * @export
 * @interface PushDevice
 */
export interface PushDevice {
    /**
     * 
     * @type {string}
     * @memberof PushDevice
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PushDevice
     */
    deviceHash: string;
    /**
     * 
     * @type {string}
     * @memberof PushDevice
     */
    userAgent?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PushDevice
     */
    lastUsedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PushDevice
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the PushDevice interface.
 */
export function instanceOfPushDevice(value: object): value is PushDevice {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('deviceHash' in value) || value['deviceHash'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PushDeviceFromJSON(json: any): PushDevice {
    return PushDeviceFromJSONTyped(json, false);
}

export function PushDeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PushDevice {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'deviceHash': json['device_hash'],
        'userAgent': json['user_agent'] == null ? undefined : json['user_agent'],
        'lastUsedAt': json['last_used_at'] == null ? undefined : (new Date(json['last_used_at'])),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function PushDeviceToJSON(json: any): PushDevice {
    return PushDeviceToJSONTyped(json, false);
}

export function PushDeviceToJSONTyped(value?: PushDevice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'device_hash': value['deviceHash'],
        'user_agent': value['userAgent'],
        'last_used_at': value['lastUsedAt'] == null ? undefined : ((value['lastUsedAt'] as any).toISOString()),
        'created_at': ((value['createdAt']).toISOString()),
    };
}

