/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response of ``POST /auth/reset_password_request``.
 * 
 * ``grant_id`` publicly identifies the recovery request (RFC 8628's
 * device_code/user_code split: the grant is the identifier, the emailed
 * 6-digit code is the only secret). Unknown emails get a random,
 * indistinguishable grant id so the response never reveals whether an
 * account exists.
 * @export
 * @interface RecoveryGrant
 */
export interface RecoveryGrant {
    /**
     * 
     * @type {string}
     * @memberof RecoveryGrant
     */
    grantId: string;
}

/**
 * Check if a given object implements the RecoveryGrant interface.
 */
export function instanceOfRecoveryGrant(value: object): value is RecoveryGrant {
    if (!('grantId' in value) || value['grantId'] === undefined) return false;
    return true;
}

export function RecoveryGrantFromJSON(json: any): RecoveryGrant {
    return RecoveryGrantFromJSONTyped(json, false);
}

export function RecoveryGrantFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryGrant {
    if (json == null) {
        return json;
    }
    return {
        
        'grantId': json['grant_id'],
    };
}

export function RecoveryGrantToJSON(json: any): RecoveryGrant {
    return RecoveryGrantToJSONTyped(json, false);
}

export function RecoveryGrantToJSONTyped(value?: RecoveryGrant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grant_id': value['grantId'],
    };
}

