/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthenticatorAttestationResponse } from './AuthenticatorAttestationResponse';
import {
    AuthenticatorAttestationResponseFromJSON,
    AuthenticatorAttestationResponseFromJSONTyped,
    AuthenticatorAttestationResponseToJSON,
    AuthenticatorAttestationResponseToJSONTyped,
} from './AuthenticatorAttestationResponse';

/**
 * Body of POST /webauthn/register (registration ceremony output).
 * 
 * Ignores (rather than forbids) unknown extras for forward compatibility
 * with newer browsers — py_webauthn only needs the fields declared here.
 * @export
 * @interface RegistrationCredential
 */
export interface RegistrationCredential {
    /**
     * 
     * @type {string}
     * @memberof RegistrationCredential
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationCredential
     */
    rawId: string;
    /**
     * 
     * @type {AuthenticatorAttestationResponse}
     * @memberof RegistrationCredential
     */
    response: AuthenticatorAttestationResponse;
    /**
     * 
     * @type {string}
     * @memberof RegistrationCredential
     */
    type: RegistrationCredentialTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof RegistrationCredential
     */
    authenticatorAttachment?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof RegistrationCredential
     */
    clientExtensionResults?: { [key: string]: any; } | null;
}


/**
 * @export
 */
export const RegistrationCredentialTypeEnum = {
    PublicKey: 'public-key'
} as const;
export type RegistrationCredentialTypeEnum = typeof RegistrationCredentialTypeEnum[keyof typeof RegistrationCredentialTypeEnum];


/**
 * Check if a given object implements the RegistrationCredential interface.
 */
export function instanceOfRegistrationCredential(value: object): value is RegistrationCredential {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('rawId' in value) || value['rawId'] === undefined) return false;
    if (!('response' in value) || value['response'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function RegistrationCredentialFromJSON(json: any): RegistrationCredential {
    return RegistrationCredentialFromJSONTyped(json, false);
}

export function RegistrationCredentialFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationCredential {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'rawId': json['rawId'],
        'response': AuthenticatorAttestationResponseFromJSON(json['response']),
        'type': json['type'],
        'authenticatorAttachment': json['authenticatorAttachment'] == null ? undefined : json['authenticatorAttachment'],
        'clientExtensionResults': json['clientExtensionResults'] == null ? undefined : json['clientExtensionResults'],
    };
}

export function RegistrationCredentialToJSON(json: any): RegistrationCredential {
    return RegistrationCredentialToJSONTyped(json, false);
}

export function RegistrationCredentialToJSONTyped(value?: RegistrationCredential | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'rawId': value['rawId'],
        'response': AuthenticatorAttestationResponseToJSON(value['response']),
        'type': value['type'],
        'authenticatorAttachment': value['authenticatorAttachment'],
        'clientExtensionResults': value['clientExtensionResults'],
    };
}

