/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Response } from './Response';
import {
    ResponseFromJSON,
    ResponseFromJSONTyped,
    ResponseToJSON,
    ResponseToJSONTyped,
} from './Response';
import type { Event } from './Event';
import {
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
    EventToJSONTyped,
} from './Event';
import type { MyProfileUpdate } from './MyProfileUpdate';
import {
    MyProfileUpdateFromJSON,
    MyProfileUpdateFromJSONTyped,
    MyProfileUpdateToJSON,
    MyProfileUpdateToJSONTyped,
} from './MyProfileUpdate';

/**
 * 
 * @export
 * @interface Res
 */
export interface Res {
    /**
     * 
     * @type {Event}
     * @memberof Res
     */
    event: Event;
    /**
     * 
     * @type {MyProfileUpdate}
     * @memberof Res
     */
    user: MyProfileUpdate;
    /**
     * 
     * @type {Response}
     * @memberof Res
     */
    response?: Response | null;
}

/**
 * Check if a given object implements the Res interface.
 */
export function instanceOfRes(value: object): value is Res {
    if (!('event' in value) || value['event'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function ResFromJSON(json: any): Res {
    return ResFromJSONTyped(json, false);
}

export function ResFromJSONTyped(json: any, ignoreDiscriminator: boolean): Res {
    if (json == null) {
        return json;
    }
    return {
        
        'event': EventFromJSON(json['event']),
        'user': MyProfileUpdateFromJSON(json['user']),
        'response': json['response'] == null ? undefined : ResponseFromJSON(json['response']),
    };
}

export function ResToJSON(json: any): Res {
    return ResToJSONTyped(json, false);
}

export function ResToJSONTyped(value?: Res | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event': EventToJSON(value['event']),
        'user': MyProfileUpdateToJSON(value['user']),
        'response': ResponseToJSON(value['response']),
    };
}

