/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Residentkey
 */
export interface Residentkey {
}

/**
 * Check if a given object implements the Residentkey interface.
 */
export function instanceOfResidentkey(value: object): value is Residentkey {
    return true;
}

export function ResidentkeyFromJSON(json: any): Residentkey {
    return ResidentkeyFromJSONTyped(json, false);
}

export function ResidentkeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Residentkey {
    return json;
}

export function ResidentkeyToJSON(json: any): Residentkey {
    return ResidentkeyToJSONTyped(json, false);
}

export function ResidentkeyToJSONTyped(value?: Residentkey | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

