/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseChangeUser
 */
export interface ResponseChangeUser {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    firstName: string;
    /**
     * 
     */
    lastName: string;
}

/**
 * Check if a given object implements the ResponseChangeUser interface.
 */
export function instanceOfResponseChangeUser(value: object): value is ResponseChangeUser {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('firstName' in (value as Record<string, any>)) && !('first_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['firstName'] === undefined && (value as Record<string, any>)['first_name'] === undefined)) return false;
    if ((!('lastName' in (value as Record<string, any>)) && !('last_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['lastName'] === undefined && (value as Record<string, any>)['last_name'] === undefined)) return false;
    return true;
}

export function ResponseChangeUserFromJSON(json: any): ResponseChangeUser {
    return ResponseChangeUserFromJSONTyped(json, false);
}

export function ResponseChangeUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseChangeUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
    };
}

export function ResponseChangeUserToJSON(json: any): ResponseChangeUser {
    return ResponseChangeUserToJSONTyped(json, false);
}

export function ResponseChangeUserToJSONTyped(value?: ResponseChangeUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
    };
}

