/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Event } from './Event';
import {
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
    EventToJSONTyped,
} from './Event';
import type { ResponseChangeUser } from './ResponseChangeUser';
import {
    ResponseChangeUserFromJSON,
    ResponseChangeUserFromJSONTyped,
    ResponseChangeUserToJSON,
    ResponseChangeUserToJSONTyped,
} from './ResponseChangeUser';

/**
 * 
 * @export
 * @interface ResponseChange
 */
export interface ResponseChange {
    /**
     * 
     * @type {number}
     * @memberof ResponseChange
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof ResponseChange
     */
    fromValue: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ResponseChange
     */
    toValue: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ResponseChange
     */
    changedAt: Date;
    /**
     * 
     * @type {Event}
     * @memberof ResponseChange
     */
    event: Event;
    /**
     * 
     * @type {ResponseChangeUser}
     * @memberof ResponseChange
     */
    user: ResponseChangeUser;
}

/**
 * Check if a given object implements the ResponseChange interface.
 */
export function instanceOfResponseChange(value: object): value is ResponseChange {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('fromValue' in value) || value['fromValue'] === undefined) return false;
    if (!('toValue' in value) || value['toValue'] === undefined) return false;
    if (!('changedAt' in value) || value['changedAt'] === undefined) return false;
    if (!('event' in value) || value['event'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function ResponseChangeFromJSON(json: any): ResponseChange {
    return ResponseChangeFromJSONTyped(json, false);
}

export function ResponseChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseChange {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'fromValue': json['from_value'],
        'toValue': json['to_value'],
        'changedAt': (new Date(json['changed_at'])),
        'event': EventFromJSON(json['event']),
        'user': ResponseChangeUserFromJSON(json['user']),
    };
}

export function ResponseChangeToJSON(json: any): ResponseChange {
    return ResponseChangeToJSONTyped(json, false);
}

export function ResponseChangeToJSONTyped(value?: ResponseChange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'from_value': value['fromValue'],
        'to_value': value['toValue'],
        'changed_at': ((value['changedAt']).toISOString()),
        'event': EventToJSON(value['event']),
        'user': ResponseChangeUserToJSON(value['user']),
    };
}

