/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRankingItem } from './UserRankingItem';
import {
    UserRankingItemFromJSON,
    UserRankingItemFromJSONTyped,
    UserRankingItemToJSON,
    UserRankingItemToJSONTyped,
} from './UserRankingItem';

/**
 * Full ranking for one window.
 * 
 * ``season`` is the starting year of the season (e.g. ``2024`` for the
 * 2024-2025 season), or ``None`` for the all-time aggregate across seasons.
 * @export
 * @interface SeasonRanking
 */
export interface SeasonRanking {
    /**
     * 
     * @type {number}
     * @memberof SeasonRanking
     */
    season: number | null;
    /**
     * 
     * @type {Array<UserRankingItem>}
     * @memberof SeasonRanking
     */
    items: Array<UserRankingItem>;
}

/**
 * Check if a given object implements the SeasonRanking interface.
 */
export function instanceOfSeasonRanking(value: object): value is SeasonRanking {
    if (!('season' in value) || value['season'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function SeasonRankingFromJSON(json: any): SeasonRanking {
    return SeasonRankingFromJSONTyped(json, false);
}

export function SeasonRankingFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeasonRanking {
    if (json == null) {
        return json;
    }
    return {
        
        'season': json['season'],
        'items': ((json['items'] as Array<any>).map(UserRankingItemFromJSON)),
    };
}

export function SeasonRankingToJSON(json: any): SeasonRanking {
    return SeasonRankingToJSONTyped(json, false);
}

export function SeasonRankingToJSONTyped(value?: SeasonRanking | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'season': value['season'],
        'items': ((value['items'] as Array<any>).map(UserRankingItemToJSON)),
    };
}

