/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Body of ``POST /auth/set_password`` (authenticated, no current password).
 * 
 * No confirmation field: the form has a show-password toggle, which is the
 * modern guard against typos (NIST 800-63B dropped the double-entry
 * recommendation once masking can be lifted).
 * @export
 * @interface SetPassword
 */
export interface SetPassword {
    /**
     * 
     * @type {string}
     * @memberof SetPassword
     */
    password: string;
}

/**
 * Check if a given object implements the SetPassword interface.
 */
export function instanceOfSetPassword(value: object): value is SetPassword {
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SetPasswordFromJSON(json: any): SetPassword {
    return SetPasswordFromJSONTyped(json, false);
}

export function SetPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPassword {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
    };
}

export function SetPasswordToJSON(json: any): SetPassword {
    return SetPasswordToJSONTyped(json, false);
}

export function SetPasswordToJSONTyped(value?: SetPassword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
    };
}

