/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Userverification
 */
export interface Userverification {
}

/**
 * Check if a given object implements the Userverification interface.
 */
export function instanceOfUserverification(value: object): value is Userverification {
    return true;
}

export function UserverificationFromJSON(json: any): Userverification {
    return UserverificationFromJSONTyped(json, false);
}

export function UserverificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Userverification {
    return json;
}

export function UserverificationToJSON(json: any): Userverification {
    return UserverificationToJSONTyped(json, false);
}

export function UserverificationToJSONTyped(value?: Userverification | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

