/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRankingItem } from './UserRankingItem';
import {
    UserRankingItemFromJSON,
    UserRankingItemFromJSONTyped,
    UserRankingItemToJSON,
    UserRankingItemToJSONTyped,
} from './UserRankingItem';

/**
 * 
 * @export
 * @interface UserRankings
 */
export interface UserRankings {
    /**
     * 
     * @type {Array<UserRankingItem>}
     * @memberof UserRankings
     */
    rankings: Array<UserRankingItem>;
}

/**
 * Check if a given object implements the UserRankings interface.
 */
export function instanceOfUserRankings(value: object): value is UserRankings {
    if (!('rankings' in value) || value['rankings'] === undefined) return false;
    return true;
}

export function UserRankingsFromJSON(json: any): UserRankings {
    return UserRankingsFromJSONTyped(json, false);
}

export function UserRankingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRankings {
    if (json == null) {
        return json;
    }
    return {
        
        'rankings': ((json['rankings'] as Array<any>).map(UserRankingItemFromJSON)),
    };
}

export function UserRankingsToJSON(json: any): UserRankings {
    return UserRankingsToJSONTyped(json, false);
}

export function UserRankingsToJSONTyped(value?: UserRankings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rankings': ((value['rankings'] as Array<any>).map(UserRankingItemToJSON)),
    };
}

