/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RankingInfo } from './RankingInfo';
import {
    RankingInfoFromJSON,
    RankingInfoFromJSONTyped,
    RankingInfoToJSON,
    RankingInfoToJSONTyped,
} from './RankingInfo';
import type { Profile } from './Profile';
import {
    ProfileFromJSON,
    ProfileFromJSONTyped,
    ProfileToJSON,
    ProfileToJSONTyped,
} from './Profile';

/**
 * 
 * @export
 * @interface UserRankingItem
 */
export interface UserRankingItem {
    /**
     * 
     * @type {Profile}
     * @memberof UserRankingItem
     */
    user: Profile;
    /**
     * 
     * @type {RankingInfo}
     * @memberof UserRankingItem
     */
    ranks: RankingInfo;
}

/**
 * Check if a given object implements the UserRankingItem interface.
 */
export function instanceOfUserRankingItem(value: object): value is UserRankingItem {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('ranks' in value) || value['ranks'] === undefined) return false;
    return true;
}

export function UserRankingItemFromJSON(json: any): UserRankingItem {
    return UserRankingItemFromJSONTyped(json, false);
}

export function UserRankingItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRankingItem {
    if (json == null) {
        return json;
    }
    return {
        
        'user': ProfileFromJSON(json['user']),
        'ranks': RankingInfoFromJSON(json['ranks']),
    };
}

export function UserRankingItemToJSON(json: any): UserRankingItem {
    return UserRankingItemToJSONTyped(json, false);
}

export function UserRankingItemToJSONTyped(value?: UserRankingItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': ProfileToJSON(value['user']),
        'ranks': RankingInfoToJSON(value['ranks']),
    };
}

