/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for VAPID public key response.
 * @export
 * @interface VapidPublicKeyResponse
 */
export interface VapidPublicKeyResponse {
    /**
     * 
     * @type {string}
     * @memberof VapidPublicKeyResponse
     */
    publicKey: string;
}

/**
 * Check if a given object implements the VapidPublicKeyResponse interface.
 */
export function instanceOfVapidPublicKeyResponse(value: object): value is VapidPublicKeyResponse {
    if (!('publicKey' in value) || value['publicKey'] === undefined) return false;
    return true;
}

export function VapidPublicKeyResponseFromJSON(json: any): VapidPublicKeyResponse {
    return VapidPublicKeyResponseFromJSONTyped(json, false);
}

export function VapidPublicKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VapidPublicKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'publicKey': json['public_key'],
    };
}

export function VapidPublicKeyResponseToJSON(json: any): VapidPublicKeyResponse {
    return VapidPublicKeyResponseToJSONTyped(json, false);
}

export function VapidPublicKeyResponseToJSONTyped(value?: VapidPublicKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'public_key': value['publicKey'],
    };
}

