/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Id } from './Id';
import {
    IdFromJSON,
    IdFromJSONTyped,
    IdToJSON,
    IdToJSONTyped,
} from './Id';

/**
 * 
 * @export
 * @interface WebAuthnRp
 */
export interface WebAuthnRp {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof WebAuthnRp
     */
    name: string;
    /**
     * 
     * @type {Id}
     * @memberof WebAuthnRp
     */
    id?: Id;
}

/**
 * Check if a given object implements the WebAuthnRp interface.
 */
export function instanceOfWebAuthnRp(value: object): value is WebAuthnRp {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function WebAuthnRpFromJSON(json: any): WebAuthnRp {
    return WebAuthnRpFromJSONTyped(json, false);
}

export function WebAuthnRpFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebAuthnRp {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'name': json['name'],
        'id': json['id'] == null ? undefined : IdFromJSON(json['id']),
    };
}

export function WebAuthnRpToJSON(json: any): WebAuthnRp {
    return WebAuthnRpToJSONTyped(json, false);
}

export function WebAuthnRpToJSONTyped(value?: WebAuthnRp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'name': value['name'],
        'id': IdToJSON(value['id']),
    };
}

