/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Transports } from './Transports';
import {
    TransportsFromJSON,
    TransportsFromJSONTyped,
    TransportsToJSON,
    TransportsToJSONTyped,
} from './Transports';

/**
 * 
 * @export
 * @interface WebAuthnCredentialDescriptor
 */
export interface WebAuthnCredentialDescriptor {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof WebAuthnCredentialDescriptor
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WebAuthnCredentialDescriptor
     */
    type: string;
    /**
     * 
     * @type {Transports}
     * @memberof WebAuthnCredentialDescriptor
     */
    transports?: Transports;
}

/**
 * Check if a given object implements the WebAuthnCredentialDescriptor interface.
 */
export function instanceOfWebAuthnCredentialDescriptor(value: object): value is WebAuthnCredentialDescriptor {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function WebAuthnCredentialDescriptorFromJSON(json: any): WebAuthnCredentialDescriptor {
    return WebAuthnCredentialDescriptorFromJSONTyped(json, false);
}

export function WebAuthnCredentialDescriptorFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebAuthnCredentialDescriptor {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'type': json['type'],
        'transports': json['transports'] == null ? undefined : TransportsFromJSON(json['transports']),
    };
}

export function WebAuthnCredentialDescriptorToJSON(json: any): WebAuthnCredentialDescriptor {
    return WebAuthnCredentialDescriptorToJSONTyped(json, false);
}

export function WebAuthnCredentialDescriptorToJSONTyped(value?: WebAuthnCredentialDescriptor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'type': value['type'],
        'transports': TransportsToJSON(value['transports']),
    };
}

