/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebAuthnPubKeyCredParam
 */
export interface WebAuthnPubKeyCredParam {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof WebAuthnPubKeyCredParam
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof WebAuthnPubKeyCredParam
     */
    alg: number;
}

/**
 * Check if a given object implements the WebAuthnPubKeyCredParam interface.
 */
export function instanceOfWebAuthnPubKeyCredParam(value: object): value is WebAuthnPubKeyCredParam {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('alg' in value) || value['alg'] === undefined) return false;
    return true;
}

export function WebAuthnPubKeyCredParamFromJSON(json: any): WebAuthnPubKeyCredParam {
    return WebAuthnPubKeyCredParamFromJSONTyped(json, false);
}

export function WebAuthnPubKeyCredParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebAuthnPubKeyCredParam {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['type'],
        'alg': json['alg'],
    };
}

export function WebAuthnPubKeyCredParamToJSON(json: any): WebAuthnPubKeyCredParam {
    return WebAuthnPubKeyCredParamToJSONTyped(json, false);
}

export function WebAuthnPubKeyCredParamToJSONTyped(value?: WebAuthnPubKeyCredParam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'type': value['type'],
        'alg': value['alg'],
    };
}

