"""Add Roles

Revision ID: 25514b36d9bb
Revises: 0911c27a457b
Create Date: 2024-11-24 00:31:43.636648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25514b36d9bb'
down_revision: Union[str, None] = '0911c27a457b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_role_association_table',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.drop_table('group_permission_association_table')
    op.drop_table('permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tag', sa.VARCHAR(length=127), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=127), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='permissions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('group_permission_association_table',
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('permission_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='group_permission_association_table_group_id_fkey'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='group_permission_association_table_permission_id_fkey')
    )
    op.drop_table('group_role_association_table')
    op.drop_table('roles')
    # ### end Alembic commands ###
