"""Remove role id

Revision ID: 43cc4865f539
Revises: 25514b36d9bb
Create Date: 2024-11-24 23:06:00.440008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43cc4865f539'
down_revision: Union[str, None] = '25514b36d9bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', sa.VARCHAR(length=127), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
