"""Add receives_emails

Revision ID: 569f76cc1c7f
Revises: 43cc4865f539
Create Date: 2024-12-05 18:05:29.293917

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "569f76cc1c7f"
down_revision: Union[str, None] = "43cc4865f539"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "receives_emails", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "receives_emails")
    # ### end Alembic commands ###
