"""Add passkeys

Revision ID: 61ce42e386ec
Revises: 092f24595c11
Create Date: 2025-04-05 13:09:38.149655

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61ce42e386ec"
down_revision: Union[str, None] = "092f24595c11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("passkey_user_id", sa.LargeBinary(), nullable=True)
    )
    op.create_index("idx_passkey_user_id", "users", ["passkey_user_id"], unique=True)
    op.create_table(
        "passkeys",
        sa.Column("passkey_user_id", sa.LargeBinary(), nullable=False),
        sa.Column("credential_id", sa.LargeBinary(), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("transports", sa.String(), nullable=False),
        sa.Column("device_type", sa.String(), nullable=False),
        sa.Column("back_up", sa.Boolean(), nullable=False),
        sa.Column("aaguid", sa.String(), nullable=False),
        sa.Column("last_use_at", sa.DateTime(), nullable=True),
        sa.Column("last_use_ip", sa.String(), nullable=True),
        sa.Column("last_use_ua", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["passkey_user_id"],
            ["users.passkey_user_id"],
        ),
        sa.PrimaryKeyConstraint("credential_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("passkeys")
    op.drop_index("idx_passkey_user_id", table_name="users")
    op.drop_column("users", "passkey_user_id")
    # ### end Alembic commands ###
