apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bagadmenru

resources:
  - postgres.yaml
  - backend-config.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-config.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/maelgui/bagadmenru-v5/backend
    newTag: latest
  - name: ghcr.io/maelgui/bagadmenru-v5/frontend
    newTag: latest
