name: backend-test
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

defaults:
  run:
    working-directory: backend

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install dependencies
        run: poetry install
      - name: Run test
        run: poetry run pytest
