name: frontend-test

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run eslint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: yarn
      - run: yarn lint
  tsc:
    runs-on: ubuntu-latest
    name: Check typescript
    steps:
      - uses: actions/checkout@v4
      - run: rm $(which tsc) || true
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: yarn
      - run: yarn run tsc --version
      - run: yarn tsc
